package:
  name: mdscripts
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ./

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  noarch_python: True

requirements:
  build:
    - python
    - setuptools
    - pyqt >=5
    - setuptools_scm
    - matplotlib
    - numpy
    - scipy
    - python-graphviz

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - pyqt >=5
    - setuptools_scm
    - python-graphviz

about:
  home: https://github.com/awacha/mdscripts
  license: 3-clause BSD license
  dev_url: https://github.com/awacha/mdscripts.git
  license_family: BSD
  license_file: LICENSE
  summary: Various scripts and GUI tools for molecular dynamics simulations

app:
  entry: gmx_extract_energy
  summary: GROMACS Energy Analyzer
  type: desk

app:
  entry: gmx_rama_analyzer
  summary: GROMACS Ramachandran Plot Analyzer
  type: desk

app:
  entry: gmx_rtp_browser
  summary: GROMACS RTP Browser
  type: desk