# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mdscripts/mdpmaker/pages/barostat.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.resize(431, 300)
        self.gridLayout = QtWidgets.QGridLayout(WizardPage)
        self.gridLayout.setObjectName("gridLayout")
        self.label_49 = QtWidgets.QLabel(WizardPage)
        self.label_49.setObjectName("label_49")
        self.gridLayout.addWidget(self.label_49, 0, 0, 1, 1)
        self.pcouplComboBox = QtWidgets.QComboBox(WizardPage)
        self.pcouplComboBox.setObjectName("pcouplComboBox")
        self.pcouplComboBox.addItem("")
        self.pcouplComboBox.addItem("")
        self.gridLayout.addWidget(self.pcouplComboBox, 0, 1, 1, 1)
        self.label_50 = QtWidgets.QLabel(WizardPage)
        self.label_50.setObjectName("label_50")
        self.gridLayout.addWidget(self.label_50, 1, 0, 1, 1)
        self.pcopultypeComboBox = QtWidgets.QComboBox(WizardPage)
        self.pcopultypeComboBox.setObjectName("pcopultypeComboBox")
        self.pcopultypeComboBox.addItem("")
        self.pcopultypeComboBox.addItem("")
        self.pcopultypeComboBox.addItem("")
        self.gridLayout.addWidget(self.pcopultypeComboBox, 1, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(WizardPage)
        self.label_51.setObjectName("label_51")
        self.gridLayout.addWidget(self.label_51, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nstpcoupleSpinBox = QtWidgets.QSpinBox(WizardPage)
        self.nstpcoupleSpinBox.setMinimum(-1)
        self.nstpcoupleSpinBox.setMaximum(99999999)
        self.nstpcoupleSpinBox.setProperty("value", -1)
        self.nstpcoupleSpinBox.setObjectName("nstpcoupleSpinBox")
        self.horizontalLayout_2.addWidget(self.nstpcoupleSpinBox)
        self.nstpcoupleTimeLabel = QtWidgets.QLabel(WizardPage)
        self.nstpcoupleTimeLabel.setObjectName("nstpcoupleTimeLabel")
        self.horizontalLayout_2.addWidget(self.nstpcoupleTimeLabel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(WizardPage)
        self.label_52.setObjectName("label_52")
        self.gridLayout.addWidget(self.label_52, 3, 0, 1, 1)
        self.tau_pDoubleSpinBox = QtWidgets.QDoubleSpinBox(WizardPage)
        self.tau_pDoubleSpinBox.setDecimals(4)
        self.tau_pDoubleSpinBox.setMaximum(9999999.0)
        self.tau_pDoubleSpinBox.setProperty("value", 1.0)
        self.tau_pDoubleSpinBox.setObjectName("tau_pDoubleSpinBox")
        self.gridLayout.addWidget(self.tau_pDoubleSpinBox, 3, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(WizardPage)
        self.label_53.setObjectName("label_53")
        self.gridLayout.addWidget(self.label_53, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.compressibilityDoubleSpinBox_1 = QtWidgets.QDoubleSpinBox(WizardPage)
        self.compressibilityDoubleSpinBox_1.setObjectName("compressibilityDoubleSpinBox_1")
        self.horizontalLayout_3.addWidget(self.compressibilityDoubleSpinBox_1)
        self.compressibilityDoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(WizardPage)
        self.compressibilityDoubleSpinBox_2.setObjectName("compressibilityDoubleSpinBox_2")
        self.horizontalLayout_3.addWidget(self.compressibilityDoubleSpinBox_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(WizardPage)
        self.label_54.setObjectName("label_54")
        self.gridLayout.addWidget(self.label_54, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ref_pDoubleSpinbox_1 = QtWidgets.QDoubleSpinBox(WizardPage)
        self.ref_pDoubleSpinbox_1.setObjectName("ref_pDoubleSpinbox_1")
        self.horizontalLayout_4.addWidget(self.ref_pDoubleSpinbox_1)
        self.ref_pDoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(WizardPage)
        self.ref_pDoubleSpinBox_2.setObjectName("ref_pDoubleSpinBox_2")
        self.horizontalLayout_4.addWidget(self.ref_pDoubleSpinBox_2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(WizardPage)
        self.label_55.setObjectName("label_55")
        self.gridLayout.addWidget(self.label_55, 6, 0, 1, 1)
        self.refcoord_scalingComboBox = QtWidgets.QComboBox(WizardPage)
        self.refcoord_scalingComboBox.setObjectName("refcoord_scalingComboBox")
        self.refcoord_scalingComboBox.addItem("")
        self.refcoord_scalingComboBox.addItem("")
        self.refcoord_scalingComboBox.addItem("")
        self.gridLayout.addWidget(self.refcoord_scalingComboBox, 6, 1, 1, 1)
        self.label_49.setBuddy(self.pcouplComboBox)
        self.label_50.setBuddy(self.pcopultypeComboBox)
        self.label_51.setBuddy(self.nstpcoupleSpinBox)
        self.label_52.setBuddy(self.tau_pDoubleSpinBox)
        self.label_53.setBuddy(self.compressibilityDoubleSpinBox_1)
        self.label_54.setBuddy(self.ref_pDoubleSpinbox_1)
        self.label_55.setBuddy(self.refcoord_scalingComboBox)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)
        WizardPage.setTabOrder(self.pcouplComboBox, self.pcopultypeComboBox)
        WizardPage.setTabOrder(self.pcopultypeComboBox, self.nstpcoupleSpinBox)
        WizardPage.setTabOrder(self.nstpcoupleSpinBox, self.tau_pDoubleSpinBox)
        WizardPage.setTabOrder(self.tau_pDoubleSpinBox, self.compressibilityDoubleSpinBox_1)
        WizardPage.setTabOrder(self.compressibilityDoubleSpinBox_1, self.compressibilityDoubleSpinBox_2)
        WizardPage.setTabOrder(self.compressibilityDoubleSpinBox_2, self.ref_pDoubleSpinbox_1)
        WizardPage.setTabOrder(self.ref_pDoubleSpinbox_1, self.ref_pDoubleSpinBox_2)
        WizardPage.setTabOrder(self.ref_pDoubleSpinBox_2, self.refcoord_scalingComboBox)

    def retranslateUi(self, WizardPage):
        _translate = QtCore.QCoreApplication.translate
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage"))
        WizardPage.setTitle(_translate("WizardPage", "Pressure coupling"))
        WizardPage.setSubTitle(_translate("WizardPage", "Tune the barostat"))
        self.label_49.setText(_translate("WizardPage", "Algorithm:"))
        self.pcouplComboBox.setItemText(0, _translate("WizardPage", "Berendsen"))
        self.pcouplComboBox.setItemText(1, _translate("WizardPage", "Parrinello-Rahman"))
        self.label_50.setText(_translate("WizardPage", "Coupling type:"))
        self.pcopultypeComboBox.setItemText(0, _translate("WizardPage", "isotropic"))
        self.pcopultypeComboBox.setItemText(1, _translate("WizardPage", "semiisotropic"))
        self.pcopultypeComboBox.setItemText(2, _translate("WizardPage", "surface-tension"))
        self.label_51.setText(_translate("WizardPage", "Pressure coupling fre&quency [steps]:"))
        self.nstpcoupleSpinBox.setSpecialValueText(_translate("WizardPage", "=nstlist"))
        self.nstpcoupleTimeLabel.setText(_translate("WizardPage", "TextLabel"))
        self.label_52.setText(_translate("WizardPage", "Time constant for pressure coupling [ps]:"))
        self.label_53.setText(_translate("WizardPage", "Compressibility [&1/bar]:"))
        self.label_54.setText(_translate("WizardPage", "Reference pressure [bar]:"))
        self.label_55.setText(_translate("WizardPage", "Reference coordinate scaling:"))
        self.refcoord_scalingComboBox.setItemText(0, _translate("WizardPage", "no"))
        self.refcoord_scalingComboBox.setItemText(1, _translate("WizardPage", "all"))
        self.refcoord_scalingComboBox.setItemText(2, _translate("WizardPage", "com"))

