# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mdscripts/mdpmaker/pages/coulomb.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.resize(474, 234)
        self.gridLayout = QtWidgets.QGridLayout(WizardPage)
        self.gridLayout.setObjectName("gridLayout")
        self.label_29 = QtWidgets.QLabel(WizardPage)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 0, 0, 1, 1)
        self.coulombtypeComboBox = QtWidgets.QComboBox(WizardPage)
        self.coulombtypeComboBox.setObjectName("coulombtypeComboBox")
        self.coulombtypeComboBox.addItem("")
        self.coulombtypeComboBox.addItem("")
        self.coulombtypeComboBox.addItem("")
        self.coulombtypeComboBox.addItem("")
        self.coulombtypeComboBox.addItem("")
        self.coulombtypeComboBox.addItem("")
        self.gridLayout.addWidget(self.coulombtypeComboBox, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(WizardPage)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 1, 0, 1, 1)
        self.coulomb_modifierComboBox = QtWidgets.QComboBox(WizardPage)
        self.coulomb_modifierComboBox.setObjectName("coulomb_modifierComboBox")
        self.coulomb_modifierComboBox.addItem("")
        self.coulomb_modifierComboBox.addItem("")
        self.coulomb_modifierComboBox.addItem("")
        self.gridLayout.addWidget(self.coulomb_modifierComboBox, 1, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(WizardPage)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 2, 0, 1, 1)
        self.rcoulomb_switchDoubleSpinBox = QtWidgets.QDoubleSpinBox(WizardPage)
        self.rcoulomb_switchDoubleSpinBox.setDecimals(4)
        self.rcoulomb_switchDoubleSpinBox.setMaximum(999999.0)
        self.rcoulomb_switchDoubleSpinBox.setObjectName("rcoulomb_switchDoubleSpinBox")
        self.gridLayout.addWidget(self.rcoulomb_switchDoubleSpinBox, 2, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(WizardPage)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 3, 0, 1, 1)
        self.rcoulombDoubleSpinBox = QtWidgets.QDoubleSpinBox(WizardPage)
        self.rcoulombDoubleSpinBox.setMaximum(99999999999.0)
        self.rcoulombDoubleSpinBox.setProperty("value", 1.0)
        self.rcoulombDoubleSpinBox.setObjectName("rcoulombDoubleSpinBox")
        self.gridLayout.addWidget(self.rcoulombDoubleSpinBox, 3, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(WizardPage)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 4, 0, 1, 1)
        self.epsilon_rDoubleSpinBox = QtWidgets.QDoubleSpinBox(WizardPage)
        self.epsilon_rDoubleSpinBox.setDecimals(4)
        self.epsilon_rDoubleSpinBox.setMaximum(99999999999.0)
        self.epsilon_rDoubleSpinBox.setProperty("value", 1.0)
        self.epsilon_rDoubleSpinBox.setObjectName("epsilon_rDoubleSpinBox")
        self.gridLayout.addWidget(self.epsilon_rDoubleSpinBox, 4, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(WizardPage)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 5, 0, 1, 1)
        self.epsilon_rfDoubleSpinBox = QtWidgets.QDoubleSpinBox(WizardPage)
        self.epsilon_rfDoubleSpinBox.setDecimals(4)
        self.epsilon_rfDoubleSpinBox.setMaximum(9999999999999.0)
        self.epsilon_rfDoubleSpinBox.setObjectName("epsilon_rfDoubleSpinBox")
        self.gridLayout.addWidget(self.epsilon_rfDoubleSpinBox, 5, 1, 1, 1)
        self.label_29.setBuddy(self.coulombtypeComboBox)
        self.label_30.setBuddy(self.coulomb_modifierComboBox)
        self.label_31.setBuddy(self.rcoulomb_switchDoubleSpinBox)
        self.label_32.setBuddy(self.rcoulombDoubleSpinBox)
        self.label_33.setBuddy(self.epsilon_rDoubleSpinBox)
        self.label_34.setBuddy(self.epsilon_rfDoubleSpinBox)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        _translate = QtCore.QCoreApplication.translate
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage"))
        WizardPage.setTitle(_translate("WizardPage", "Electrostatics"))
        WizardPage.setSubTitle(_translate("WizardPage", "Coulomb interaction parameters"))
        self.label_29.setText(_translate("WizardPage", "Algorithm:"))
        self.coulombtypeComboBox.setItemText(0, _translate("WizardPage", "PME"))
        self.coulombtypeComboBox.setItemText(1, _translate("WizardPage", "PME-Switch"))
        self.coulombtypeComboBox.setItemText(2, _translate("WizardPage", "Cut-off"))
        self.coulombtypeComboBox.setItemText(3, _translate("WizardPage", "Shift"))
        self.coulombtypeComboBox.setItemText(4, _translate("WizardPage", "Reaction-Field-zero"))
        self.coulombtypeComboBox.setItemText(5, _translate("WizardPage", "Reaction-Field"))
        self.label_30.setText(_translate("WizardPage", "Modifier:"))
        self.coulomb_modifierComboBox.setItemText(0, _translate("WizardPage", "None"))
        self.coulomb_modifierComboBox.setItemText(1, _translate("WizardPage", "Potential-shift-Verlet"))
        self.coulomb_modifierComboBox.setItemText(2, _translate("WizardPage", "Potential-shift"))
        self.label_31.setText(_translate("WizardPage", "Switching distance [nm]:"))
        self.label_32.setText(_translate("WizardPage", "Short-range cut-off distance [nm]:"))
        self.label_33.setText(_translate("WizardPage", "Relative dielectric constant (&0 means infinity):"))
        self.label_34.setText(_translate("WizardPage", "Relative dielectric constant of the reaction field:"))

