# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mdscripts/mdpmaker/pages/em.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.resize(505, 234)
        self.gridLayout = QtWidgets.QGridLayout(WizardPage)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(WizardPage)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.emIntegratorComboBox = QtWidgets.QComboBox(WizardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emIntegratorComboBox.sizePolicy().hasHeightForWidth())
        self.emIntegratorComboBox.setSizePolicy(sizePolicy)
        self.emIntegratorComboBox.setObjectName("emIntegratorComboBox")
        self.emIntegratorComboBox.addItem("")
        self.emIntegratorComboBox.addItem("")
        self.emIntegratorComboBox.addItem("")
        self.gridLayout.addWidget(self.emIntegratorComboBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(WizardPage)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.emToleranceDoubleSpinBox = QtWidgets.QDoubleSpinBox(WizardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emToleranceDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.emToleranceDoubleSpinBox.setSizePolicy(sizePolicy)
        self.emToleranceDoubleSpinBox.setDecimals(4)
        self.emToleranceDoubleSpinBox.setMaximum(999.0)
        self.emToleranceDoubleSpinBox.setProperty("value", 10.0)
        self.emToleranceDoubleSpinBox.setObjectName("emToleranceDoubleSpinBox")
        self.gridLayout.addWidget(self.emToleranceDoubleSpinBox, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(WizardPage)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.emInitialStepSizeDoubleSpinBox = QtWidgets.QDoubleSpinBox(WizardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emInitialStepSizeDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.emInitialStepSizeDoubleSpinBox.setSizePolicy(sizePolicy)
        self.emInitialStepSizeDoubleSpinBox.setDecimals(4)
        self.emInitialStepSizeDoubleSpinBox.setProperty("value", 0.01)
        self.emInitialStepSizeDoubleSpinBox.setObjectName("emInitialStepSizeDoubleSpinBox")
        self.gridLayout.addWidget(self.emInitialStepSizeDoubleSpinBox, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(WizardPage)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.emnstcgsteepSpinBox = QtWidgets.QSpinBox(WizardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emnstcgsteepSpinBox.sizePolicy().hasHeightForWidth())
        self.emnstcgsteepSpinBox.setSizePolicy(sizePolicy)
        self.emnstcgsteepSpinBox.setMinimum(0)
        self.emnstcgsteepSpinBox.setMaximum(999999)
        self.emnstcgsteepSpinBox.setProperty("value", 1000)
        self.emnstcgsteepSpinBox.setObjectName("emnstcgsteepSpinBox")
        self.gridLayout.addWidget(self.emnstcgsteepSpinBox, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(WizardPage)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.emnbfgscorrSpinBox = QtWidgets.QSpinBox(WizardPage)
        self.emnbfgscorrSpinBox.setMaximum(9999999)
        self.emnbfgscorrSpinBox.setProperty("value", 10)
        self.emnbfgscorrSpinBox.setObjectName("emnbfgscorrSpinBox")
        self.gridLayout.addWidget(self.emnbfgscorrSpinBox, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(WizardPage)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.emNstepsSpinBox = QtWidgets.QSpinBox(WizardPage)
        self.emNstepsSpinBox.setMinimum(-1)
        self.emNstepsSpinBox.setMaximum(999999999)
        self.emNstepsSpinBox.setProperty("value", 0)
        self.emNstepsSpinBox.setObjectName("emNstepsSpinBox")
        self.gridLayout.addWidget(self.emNstepsSpinBox, 5, 1, 1, 1)
        self.label_2.setBuddy(self.emIntegratorComboBox)
        self.label_3.setBuddy(self.emToleranceDoubleSpinBox)
        self.label_4.setBuddy(self.emInitialStepSizeDoubleSpinBox)
        self.label_5.setBuddy(self.emnstcgsteepSpinBox)
        self.label_6.setBuddy(self.emnbfgscorrSpinBox)
        self.label_7.setBuddy(self.emNstepsSpinBox)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        _translate = QtCore.QCoreApplication.translate
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage"))
        WizardPage.setTitle(_translate("WizardPage", "Energy minimization"))
        WizardPage.setSubTitle(_translate("WizardPage", "Adjust the parameters for energy minimization"))
        self.label_2.setText(_translate("WizardPage", "Integrator:"))
        self.emIntegratorComboBox.setItemText(0, _translate("WizardPage", "steep"))
        self.emIntegratorComboBox.setItemText(1, _translate("WizardPage", "cg"))
        self.emIntegratorComboBox.setItemText(2, _translate("WizardPage", "l-bfgs"))
        self.label_3.setText(_translate("WizardPage", "Tolerance for convergence [k&J/mol/nm]:"))
        self.label_4.setText(_translate("WizardPage", "Initial step si&ze [nm]:"))
        self.label_5.setText(_translate("WizardPage", "Frequency of performing &1 steepest descent step [steps]:"))
        self.label_6.setText(_translate("WizardPage", "Number of l-BFGS correction steps [steps]:"))
        self.label_7.setText(_translate("WizardPage", "Ma&ximum number of steps [steps]:"))
        self.emNstepsSpinBox.setSpecialValueText(_translate("WizardPage", "Infinite"))

