# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mdscripts/mdpmaker/pages/freqcontrol.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.resize(491, 348)
        self.gridLayout = QtWidgets.QGridLayout(WizardPage)
        self.gridLayout.setObjectName("gridLayout")
        self.label_16 = QtWidgets.QLabel(WizardPage)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 0, 1, 1)
        self.nstxoutSpinBox = QtWidgets.QSpinBox(WizardPage)
        self.nstxoutSpinBox.setMaximum(999999999)
        self.nstxoutSpinBox.setObjectName("nstxoutSpinBox")
        self.gridLayout.addWidget(self.nstxoutSpinBox, 0, 1, 1, 1)
        self.nstxoutTimeLabel = QtWidgets.QLabel(WizardPage)
        self.nstxoutTimeLabel.setObjectName("nstxoutTimeLabel")
        self.gridLayout.addWidget(self.nstxoutTimeLabel, 0, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(WizardPage)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 0, 1, 1)
        self.nstvoutSpinBox = QtWidgets.QSpinBox(WizardPage)
        self.nstvoutSpinBox.setMaximum(999999999)
        self.nstvoutSpinBox.setObjectName("nstvoutSpinBox")
        self.gridLayout.addWidget(self.nstvoutSpinBox, 1, 1, 1, 1)
        self.nstvoutTimeLabel = QtWidgets.QLabel(WizardPage)
        self.nstvoutTimeLabel.setObjectName("nstvoutTimeLabel")
        self.gridLayout.addWidget(self.nstvoutTimeLabel, 1, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(WizardPage)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 2, 0, 1, 1)
        self.nstfoutSpinBox = QtWidgets.QSpinBox(WizardPage)
        self.nstfoutSpinBox.setMaximum(999999999)
        self.nstfoutSpinBox.setObjectName("nstfoutSpinBox")
        self.gridLayout.addWidget(self.nstfoutSpinBox, 2, 1, 1, 1)
        self.nstfoutTimeLabel = QtWidgets.QLabel(WizardPage)
        self.nstfoutTimeLabel.setObjectName("nstfoutTimeLabel")
        self.gridLayout.addWidget(self.nstfoutTimeLabel, 2, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(WizardPage)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 3, 0, 1, 1)
        self.nstlogSpinBox = QtWidgets.QSpinBox(WizardPage)
        self.nstlogSpinBox.setMaximum(999999999)
        self.nstlogSpinBox.setProperty("value", 1000)
        self.nstlogSpinBox.setObjectName("nstlogSpinBox")
        self.gridLayout.addWidget(self.nstlogSpinBox, 3, 1, 1, 1)
        self.nstlogTimeLabel = QtWidgets.QLabel(WizardPage)
        self.nstlogTimeLabel.setObjectName("nstlogTimeLabel")
        self.gridLayout.addWidget(self.nstlogTimeLabel, 3, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(WizardPage)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 4, 0, 1, 1)
        self.nstenergySpinBox = QtWidgets.QSpinBox(WizardPage)
        self.nstenergySpinBox.setMaximum(999999999)
        self.nstenergySpinBox.setProperty("value", 1000)
        self.nstenergySpinBox.setObjectName("nstenergySpinBox")
        self.gridLayout.addWidget(self.nstenergySpinBox, 4, 1, 1, 1)
        self.nstenergyTimeLabel = QtWidgets.QLabel(WizardPage)
        self.nstenergyTimeLabel.setObjectName("nstenergyTimeLabel")
        self.gridLayout.addWidget(self.nstenergyTimeLabel, 4, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(WizardPage)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 5, 0, 1, 1)
        self.nstcalcenergySpinBox = QtWidgets.QSpinBox(WizardPage)
        self.nstcalcenergySpinBox.setMaximum(999999999)
        self.nstcalcenergySpinBox.setProperty("value", 100)
        self.nstcalcenergySpinBox.setObjectName("nstcalcenergySpinBox")
        self.gridLayout.addWidget(self.nstcalcenergySpinBox, 5, 1, 1, 1)
        self.nstcalcenergyTimeLabel = QtWidgets.QLabel(WizardPage)
        self.nstcalcenergyTimeLabel.setObjectName("nstcalcenergyTimeLabel")
        self.gridLayout.addWidget(self.nstcalcenergyTimeLabel, 5, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(WizardPage)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 6, 0, 1, 1)
        self.nstxout_compressedSpinBox = QtWidgets.QSpinBox(WizardPage)
        self.nstxout_compressedSpinBox.setMaximum(999999999)
        self.nstxout_compressedSpinBox.setObjectName("nstxout_compressedSpinBox")
        self.gridLayout.addWidget(self.nstxout_compressedSpinBox, 6, 1, 1, 1)
        self.nstxout_compressedTimeLabel = QtWidgets.QLabel(WizardPage)
        self.nstxout_compressedTimeLabel.setObjectName("nstxout_compressedTimeLabel")
        self.gridLayout.addWidget(self.nstxout_compressedTimeLabel, 6, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(WizardPage)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 7, 0, 1, 1)
        self.compressed_x_precisionDoubleSpinBox = QtWidgets.QDoubleSpinBox(WizardPage)
        self.compressed_x_precisionDoubleSpinBox.setMaximum(9999999.0)
        self.compressed_x_precisionDoubleSpinBox.setProperty("value", 1000.0)
        self.compressed_x_precisionDoubleSpinBox.setObjectName("compressed_x_precisionDoubleSpinBox")
        self.gridLayout.addWidget(self.compressed_x_precisionDoubleSpinBox, 7, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(WizardPage)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 8, 0, 1, 1)
        self.compressed_x_grpsLineEdit = QtWidgets.QLineEdit(WizardPage)
        self.compressed_x_grpsLineEdit.setObjectName("compressed_x_grpsLineEdit")
        self.gridLayout.addWidget(self.compressed_x_grpsLineEdit, 8, 1, 1, 1)
        self.label_16.setBuddy(self.nstxoutSpinBox)
        self.label_17.setBuddy(self.nstvoutSpinBox)
        self.label_18.setBuddy(self.nstfoutSpinBox)
        self.label_19.setBuddy(self.nstlogSpinBox)
        self.label_20.setBuddy(self.nstenergySpinBox)
        self.label_21.setBuddy(self.nstcalcenergySpinBox)
        self.label_22.setBuddy(self.nstxout_compressedSpinBox)
        self.label_23.setBuddy(self.compressed_x_precisionDoubleSpinBox)
        self.label_24.setBuddy(self.compressed_x_grpsLineEdit)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        _translate = QtCore.QCoreApplication.translate
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage"))
        WizardPage.setTitle(_translate("WizardPage", "O&utput control"))
        WizardPage.setSubTitle(_translate("WizardPage", "Output / calculation frequencies"))
        self.label_16.setText(_translate("WizardPage", "Write coordinates every n-th step:"))
        self.nstxoutTimeLabel.setText(_translate("WizardPage", "TextLabel"))
        self.label_17.setText(_translate("WizardPage", "Write velocities every n-th step:"))
        self.nstvoutTimeLabel.setText(_translate("WizardPage", "TextLabel"))
        self.label_18.setText(_translate("WizardPage", "Write forces every &n-th step:"))
        self.nstfoutTimeLabel.setText(_translate("WizardPage", "TextLabel"))
        self.label_19.setText(_translate("WizardPage", "Write &log file every n-th step:"))
        self.nstlogTimeLabel.setText(_translate("WizardPage", "TextLabel"))
        self.label_20.setText(_translate("WizardPage", "Write energy every n-&th step:"))
        self.nstenergyTimeLabel.setText(_translate("WizardPage", "TextLabel"))
        self.label_21.setText(_translate("WizardPage", "Calculate energies every n-th step:"))
        self.nstcalcenergyTimeLabel.setText(_translate("WizardPage", "TextLabel"))
        self.label_22.setText(_translate("WizardPage", "Write &XTC file every n-th step:"))
        self.nstxout_compressedTimeLabel.setText(_translate("WizardPage", "TextLabel"))
        self.label_23.setText(_translate("WizardPage", "Precision of XTC files:"))
        self.label_24.setText(_translate("WizardPage", "&Groups to write to XTC files (space separated list):"))
        self.compressed_x_grpsLineEdit.setText(_translate("WizardPage", "System"))

