# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mdscripts/mdpmaker/pages/integrator.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.resize(541, 300)
        self.gridLayout = QtWidgets.QGridLayout(WizardPage)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(WizardPage)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.timeStepDoubleSpinBox = QtWidgets.QDoubleSpinBox(WizardPage)
        self.timeStepDoubleSpinBox.setDecimals(10)
        self.timeStepDoubleSpinBox.setMaximum(99999999.0)
        self.timeStepDoubleSpinBox.setProperty("value", 0.002)
        self.timeStepDoubleSpinBox.setObjectName("timeStepDoubleSpinBox")
        self.gridLayout.addWidget(self.timeStepDoubleSpinBox, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(WizardPage)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.nstepsSpinBox = QtWidgets.QSpinBox(WizardPage)
        self.nstepsSpinBox.setMaximum(999999999)
        self.nstepsSpinBox.setObjectName("nstepsSpinBox")
        self.gridLayout.addWidget(self.nstepsSpinBox, 1, 1, 1, 1)
        self.nstepsTimeLabel = QtWidgets.QLabel(WizardPage)
        self.nstepsTimeLabel.setObjectName("nstepsTimeLabel")
        self.gridLayout.addWidget(self.nstepsTimeLabel, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(WizardPage)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.commTypeComboBox = QtWidgets.QComboBox(WizardPage)
        self.commTypeComboBox.setObjectName("commTypeComboBox")
        self.commTypeComboBox.addItem("")
        self.commTypeComboBox.addItem("")
        self.commTypeComboBox.addItem("")
        self.commTypeComboBox.addItem("")
        self.gridLayout.addWidget(self.commTypeComboBox, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(WizardPage)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.nstcommSpinBox = QtWidgets.QSpinBox(WizardPage)
        self.nstcommSpinBox.setMaximum(999999999)
        self.nstcommSpinBox.setObjectName("nstcommSpinBox")
        self.gridLayout.addWidget(self.nstcommSpinBox, 3, 1, 1, 1)
        self.nstcommTimeLabel = QtWidgets.QLabel(WizardPage)
        self.nstcommTimeLabel.setObjectName("nstcommTimeLabel")
        self.gridLayout.addWidget(self.nstcommTimeLabel, 3, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(WizardPage)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 4, 0, 1, 1)
        self.commGrpsLineEdit = QtWidgets.QLineEdit(WizardPage)
        self.commGrpsLineEdit.setObjectName("commGrpsLineEdit")
        self.gridLayout.addWidget(self.commGrpsLineEdit, 4, 1, 1, 1)
        self.timeStepTimeLabel = QtWidgets.QLabel(WizardPage)
        self.timeStepTimeLabel.setObjectName("timeStepTimeLabel")
        self.gridLayout.addWidget(self.timeStepTimeLabel, 0, 2, 1, 1)
        self.label_9.setBuddy(self.timeStepDoubleSpinBox)
        self.label_10.setBuddy(self.nstepsSpinBox)
        self.label_11.setBuddy(self.commTypeComboBox)
        self.label_12.setBuddy(self.nstcommSpinBox)
        self.label_13.setBuddy(self.commGrpsLineEdit)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        _translate = QtCore.QCoreApplication.translate
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage"))
        WizardPage.setTitle(_translate("WizardPage", "MD Integrator"))
        WizardPage.setSubTitle(_translate("WizardPage", "Choose the main parameters for the MD simulations"))
        self.label_9.setText(_translate("WizardPage", "Time step [ps]:"))
        self.label_10.setText(_translate("WizardPage", "Number of steps:"))
        self.nstepsTimeLabel.setText(_translate("WizardPage", "TextLabel"))
        self.label_11.setText(_translate("WizardPage", "Center of mass motion (COMM) removal:"))
        self.commTypeComboBox.setItemText(0, _translate("WizardPage", "Linear"))
        self.commTypeComboBox.setItemText(1, _translate("WizardPage", "Angular"))
        self.commTypeComboBox.setItemText(2, _translate("WizardPage", "Linear-acceleration-correction"))
        self.commTypeComboBox.setItemText(3, _translate("WizardPage", "None"))
        self.label_12.setText(_translate("WizardPage", "Fre&quency for COMM removal [steps]:"))
        self.nstcommTimeLabel.setText(_translate("WizardPage", "TextLabel"))
        self.label_13.setText(_translate("WizardPage", "COMM groups [space separated list]:"))
        self.commGrpsLineEdit.setText(_translate("WizardPage", "System"))
        self.timeStepTimeLabel.setText(_translate("WizardPage", "TextLabel"))

