# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mdscripts/mdpmaker/pages/neighboursearch.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.resize(514, 300)
        self.gridLayout = QtWidgets.QGridLayout(WizardPage)
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(WizardPage)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(WizardPage)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 0, 1, 1)
        self.nstlistSpinBox = QtWidgets.QSpinBox(WizardPage)
        self.nstlistSpinBox.setObjectName("nstlistSpinBox")
        self.gridLayout.addWidget(self.nstlistSpinBox, 1, 1, 1, 1)
        self.nstListTimeLabel = QtWidgets.QLabel(WizardPage)
        self.nstListTimeLabel.setObjectName("nstListTimeLabel")
        self.gridLayout.addWidget(self.nstListTimeLabel, 1, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(WizardPage)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 2, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(WizardPage)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 3, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(WizardPage)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 4, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(WizardPage)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 5, 0, 1, 1)
        self.verlet_buffer_toleranceDoubleSpinBox = QtWidgets.QDoubleSpinBox(WizardPage)
        self.verlet_buffer_toleranceDoubleSpinBox.setDecimals(6)
        self.verlet_buffer_toleranceDoubleSpinBox.setMaximum(999999999999.0)
        self.verlet_buffer_toleranceDoubleSpinBox.setProperty("value", 0.005)
        self.verlet_buffer_toleranceDoubleSpinBox.setObjectName("verlet_buffer_toleranceDoubleSpinBox")
        self.gridLayout.addWidget(self.verlet_buffer_toleranceDoubleSpinBox, 4, 1, 1, 2)
        self.rlistDoubleSpinBox = QtWidgets.QDoubleSpinBox(WizardPage)
        self.rlistDoubleSpinBox.setDecimals(4)
        self.rlistDoubleSpinBox.setMaximum(999999999999.0)
        self.rlistDoubleSpinBox.setProperty("value", 0.01)
        self.rlistDoubleSpinBox.setObjectName("rlistDoubleSpinBox")
        self.gridLayout.addWidget(self.rlistDoubleSpinBox, 5, 1, 1, 2)
        self.pbcComboBox = QtWidgets.QComboBox(WizardPage)
        self.pbcComboBox.setObjectName("pbcComboBox")
        self.pbcComboBox.addItem("")
        self.pbcComboBox.addItem("")
        self.pbcComboBox.addItem("")
        self.gridLayout.addWidget(self.pbcComboBox, 3, 1, 1, 2)
        self.ns_typeComboBox = QtWidgets.QComboBox(WizardPage)
        self.ns_typeComboBox.setObjectName("ns_typeComboBox")
        self.ns_typeComboBox.addItem("")
        self.ns_typeComboBox.addItem("")
        self.gridLayout.addWidget(self.ns_typeComboBox, 2, 1, 1, 2)
        self.cutoff_schemeComboBox = QtWidgets.QComboBox(WizardPage)
        self.cutoff_schemeComboBox.setObjectName("cutoff_schemeComboBox")
        self.cutoff_schemeComboBox.addItem("")
        self.cutoff_schemeComboBox.addItem("")
        self.gridLayout.addWidget(self.cutoff_schemeComboBox, 0, 1, 1, 2)
        self.label_14.setBuddy(self.cutoff_schemeComboBox)
        self.label_15.setBuddy(self.nstlistSpinBox)
        self.label_25.setBuddy(self.ns_typeComboBox)
        self.label_26.setBuddy(self.pbcComboBox)
        self.label_27.setBuddy(self.verlet_buffer_toleranceDoubleSpinBox)
        self.label_28.setBuddy(self.rlistDoubleSpinBox)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)
        WizardPage.setTabOrder(self.cutoff_schemeComboBox, self.nstlistSpinBox)
        WizardPage.setTabOrder(self.nstlistSpinBox, self.ns_typeComboBox)
        WizardPage.setTabOrder(self.ns_typeComboBox, self.pbcComboBox)
        WizardPage.setTabOrder(self.pbcComboBox, self.verlet_buffer_toleranceDoubleSpinBox)
        WizardPage.setTabOrder(self.verlet_buffer_toleranceDoubleSpinBox, self.rlistDoubleSpinBox)

    def retranslateUi(self, WizardPage):
        _translate = QtCore.QCoreApplication.translate
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage"))
        WizardPage.setTitle(_translate("WizardPage", "Neighbour searching"))
        WizardPage.setSubTitle(_translate("WizardPage", "Neighbour search options"))
        self.label_14.setText(_translate("WizardPage", "Cutoff-scheme:"))
        self.label_15.setText(_translate("WizardPage", "Neighbour list update fre&quency [steps]:"))
        self.nstListTimeLabel.setText(_translate("WizardPage", "TextLabel"))
        self.label_25.setText(_translate("WizardPage", "Neighbour search type:"))
        self.label_26.setText(_translate("WizardPage", "Periodic boundary conditions:"))
        self.label_27.setText(_translate("WizardPage", "Verlet buffer tolerance [k&J/mol/ps]:"))
        self.label_28.setText(_translate("WizardPage", "Cut-off distance for the neighbour list [nm]:"))
        self.pbcComboBox.setItemText(0, _translate("WizardPage", "xyz"))
        self.pbcComboBox.setItemText(1, _translate("WizardPage", "xy"))
        self.pbcComboBox.setItemText(2, _translate("WizardPage", "no"))
        self.ns_typeComboBox.setItemText(0, _translate("WizardPage", "grid"))
        self.ns_typeComboBox.setItemText(1, _translate("WizardPage", "simple"))
        self.cutoff_schemeComboBox.setItemText(0, _translate("WizardPage", "Verlet"))
        self.cutoff_schemeComboBox.setItemText(1, _translate("WizardPage", "Group"))

