# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mdscripts/mdpmaker/pages/thermostat.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.resize(518, 342)
        self.gridLayout = QtWidgets.QGridLayout(WizardPage)
        self.gridLayout.setObjectName("gridLayout")
        self.label_42 = QtWidgets.QLabel(WizardPage)
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 0, 0, 1, 1)
        self.tcouplComboBox = QtWidgets.QComboBox(WizardPage)
        self.tcouplComboBox.setObjectName("tcouplComboBox")
        self.tcouplComboBox.addItem("")
        self.tcouplComboBox.addItem("")
        self.tcouplComboBox.addItem("")
        self.gridLayout.addWidget(self.tcouplComboBox, 0, 1, 1, 2)
        self.label_43 = QtWidgets.QLabel(WizardPage)
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 1, 0, 1, 1)
        self.nsttcoupleSpinBox = QtWidgets.QSpinBox(WizardPage)
        self.nsttcoupleSpinBox.setMinimum(-1)
        self.nsttcoupleSpinBox.setProperty("value", -1)
        self.nsttcoupleSpinBox.setObjectName("nsttcoupleSpinBox")
        self.gridLayout.addWidget(self.nsttcoupleSpinBox, 1, 1, 1, 1)
        self.nsttcoupleTimeLabel = QtWidgets.QLabel(WizardPage)
        self.nsttcoupleTimeLabel.setObjectName("nsttcoupleTimeLabel")
        self.gridLayout.addWidget(self.nsttcoupleTimeLabel, 1, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(WizardPage)
        self.label_45.setObjectName("label_45")
        self.gridLayout.addWidget(self.label_45, 2, 0, 1, 1)
        self.tc_grpsLineEdit = QtWidgets.QLineEdit(WizardPage)
        self.tc_grpsLineEdit.setObjectName("tc_grpsLineEdit")
        self.gridLayout.addWidget(self.tc_grpsLineEdit, 2, 1, 1, 2)
        self.label_46 = QtWidgets.QLabel(WizardPage)
        self.label_46.setObjectName("label_46")
        self.gridLayout.addWidget(self.label_46, 3, 0, 1, 1)
        self.ref_tDoubleSpinBox = QtWidgets.QDoubleSpinBox(WizardPage)
        self.ref_tDoubleSpinBox.setDecimals(4)
        self.ref_tDoubleSpinBox.setMaximum(9999999.0)
        self.ref_tDoubleSpinBox.setProperty("value", 300.0)
        self.ref_tDoubleSpinBox.setObjectName("ref_tDoubleSpinBox")
        self.gridLayout.addWidget(self.ref_tDoubleSpinBox, 3, 1, 1, 2)
        self.label_47 = QtWidgets.QLabel(WizardPage)
        self.label_47.setObjectName("label_47")
        self.gridLayout.addWidget(self.label_47, 4, 0, 1, 1)
        self.tau_tDoubleSpinBox = QtWidgets.QDoubleSpinBox(WizardPage)
        self.tau_tDoubleSpinBox.setDecimals(4)
        self.tau_tDoubleSpinBox.setMaximum(999999999999.0)
        self.tau_tDoubleSpinBox.setProperty("value", 1.0)
        self.tau_tDoubleSpinBox.setObjectName("tau_tDoubleSpinBox")
        self.gridLayout.addWidget(self.tau_tDoubleSpinBox, 4, 1, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(WizardPage)
        self.groupBox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_44 = QtWidgets.QLabel(self.groupBox)
        self.label_44.setObjectName("label_44")
        self.gridLayout_9.addWidget(self.label_44, 0, 0, 1, 1)
        self.gen_tempDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.gen_tempDoubleSpinBox.setDecimals(4)
        self.gen_tempDoubleSpinBox.setMaximum(99999999999.0)
        self.gen_tempDoubleSpinBox.setProperty("value", 300.0)
        self.gen_tempDoubleSpinBox.setObjectName("gen_tempDoubleSpinBox")
        self.gridLayout_9.addWidget(self.gen_tempDoubleSpinBox, 0, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBox)
        self.label_48.setObjectName("label_48")
        self.gridLayout_9.addWidget(self.label_48, 1, 0, 1, 1)
        self.gen_seedSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.gen_seedSpinBox.setMinimum(-1)
        self.gen_seedSpinBox.setMaximum(999999999)
        self.gen_seedSpinBox.setProperty("value", -1)
        self.gen_seedSpinBox.setObjectName("gen_seedSpinBox")
        self.gridLayout_9.addWidget(self.gen_seedSpinBox, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 5, 0, 1, 3)
        self.label_42.setBuddy(self.tcouplComboBox)
        self.label_43.setBuddy(self.nsttcoupleSpinBox)
        self.label_45.setBuddy(self.tc_grpsLineEdit)
        self.label_46.setBuddy(self.ref_tDoubleSpinBox)
        self.label_47.setBuddy(self.tau_tDoubleSpinBox)
        self.label_44.setBuddy(self.gen_tempDoubleSpinBox)
        self.label_48.setBuddy(self.gen_seedSpinBox)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        _translate = QtCore.QCoreApplication.translate
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage"))
        WizardPage.setTitle(_translate("WizardPage", "Temperature coupling"))
        WizardPage.setSubTitle(_translate("WizardPage", "Thermostat parameters"))
        self.label_42.setText(_translate("WizardPage", "A&lgorithm:"))
        self.tcouplComboBox.setItemText(0, _translate("WizardPage", "berendsen"))
        self.tcouplComboBox.setItemText(1, _translate("WizardPage", "nose-hoover"))
        self.tcouplComboBox.setItemText(2, _translate("WizardPage", "v-rescale"))
        self.label_43.setText(_translate("WizardPage", "Temperature coupling fre&quency [steps]:"))
        self.nsttcoupleSpinBox.setSpecialValueText(_translate("WizardPage", "=nstlist"))
        self.nsttcoupleTimeLabel.setText(_translate("WizardPage", "TextLabel"))
        self.label_45.setText(_translate("WizardPage", "&Temperature coupling groups [space separated list]:"))
        self.label_46.setText(_translate("WizardPage", "Reference temperature [&K, common for all groups]:"))
        self.label_47.setText(_translate("WizardPage", "Time constant for coupling [ps, common for all groups]:"))
        self.groupBox.setTitle(_translate("WizardPage", "Velocity &generation"))
        self.label_44.setText(_translate("WizardPage", "Temperature [K]:"))
        self.label_48.setText(_translate("WizardPage", "Ra&ndom seed:"))
        self.gen_seedSpinBox.setSpecialValueText(_translate("WizardPage", "Pseudo-random"))

