# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mdscripts/mdpmaker/pages/vdw.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_WizardPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.resize(456, 196)
        self.gridLayout = QtWidgets.QGridLayout(WizardPage)
        self.gridLayout.setObjectName("gridLayout")
        self.label_35 = QtWidgets.QLabel(WizardPage)
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 0, 0, 1, 1)
        self.vdwtypeComboBox = QtWidgets.QComboBox(WizardPage)
        self.vdwtypeComboBox.setObjectName("vdwtypeComboBox")
        self.vdwtypeComboBox.addItem("")
        self.vdwtypeComboBox.addItem("")
        self.vdwtypeComboBox.addItem("")
        self.vdwtypeComboBox.addItem("")
        self.gridLayout.addWidget(self.vdwtypeComboBox, 0, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(WizardPage)
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 1, 0, 1, 1)
        self.vdw_modifierComboBox = QtWidgets.QComboBox(WizardPage)
        self.vdw_modifierComboBox.setObjectName("vdw_modifierComboBox")
        self.vdw_modifierComboBox.addItem("")
        self.vdw_modifierComboBox.addItem("")
        self.vdw_modifierComboBox.addItem("")
        self.vdw_modifierComboBox.addItem("")
        self.vdw_modifierComboBox.addItem("")
        self.gridLayout.addWidget(self.vdw_modifierComboBox, 1, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(WizardPage)
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 2, 0, 1, 1)
        self.rvdwDoubleSpinBox = QtWidgets.QDoubleSpinBox(WizardPage)
        self.rvdwDoubleSpinBox.setDecimals(4)
        self.rvdwDoubleSpinBox.setMaximum(99999999.0)
        self.rvdwDoubleSpinBox.setProperty("value", 1.0)
        self.rvdwDoubleSpinBox.setObjectName("rvdwDoubleSpinBox")
        self.gridLayout.addWidget(self.rvdwDoubleSpinBox, 2, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(WizardPage)
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 3, 0, 1, 1)
        self.rvdw_switchDoubleSpinBox = QtWidgets.QDoubleSpinBox(WizardPage)
        self.rvdw_switchDoubleSpinBox.setMaximum(9999999999.0)
        self.rvdw_switchDoubleSpinBox.setObjectName("rvdw_switchDoubleSpinBox")
        self.gridLayout.addWidget(self.rvdw_switchDoubleSpinBox, 3, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(WizardPage)
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 4, 0, 1, 1)
        self.dispcorrComboBox = QtWidgets.QComboBox(WizardPage)
        self.dispcorrComboBox.setObjectName("dispcorrComboBox")
        self.dispcorrComboBox.addItem("")
        self.dispcorrComboBox.addItem("")
        self.dispcorrComboBox.addItem("")
        self.gridLayout.addWidget(self.dispcorrComboBox, 4, 1, 1, 1)
        self.label_35.setBuddy(self.vdwtypeComboBox)
        self.label_36.setBuddy(self.vdw_modifierComboBox)
        self.label_37.setBuddy(self.rvdwDoubleSpinBox)
        self.label_38.setBuddy(self.rvdw_switchDoubleSpinBox)
        self.label_39.setBuddy(self.dispcorrComboBox)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        _translate = QtCore.QCoreApplication.translate
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage"))
        WizardPage.setTitle(_translate("WizardPage", "Van der Waals"))
        WizardPage.setSubTitle(_translate("WizardPage", "Van der Waals interactions"))
        self.label_35.setText(_translate("WizardPage", "Algorithm:"))
        self.vdwtypeComboBox.setItemText(0, _translate("WizardPage", "Cut-off"))
        self.vdwtypeComboBox.setItemText(1, _translate("WizardPage", "PME"))
        self.vdwtypeComboBox.setItemText(2, _translate("WizardPage", "Shift"))
        self.vdwtypeComboBox.setItemText(3, _translate("WizardPage", "Switch"))
        self.label_36.setText(_translate("WizardPage", "Modifier:"))
        self.vdw_modifierComboBox.setItemText(0, _translate("WizardPage", "Potential-shift-Verlet"))
        self.vdw_modifierComboBox.setItemText(1, _translate("WizardPage", "Potential-shift"))
        self.vdw_modifierComboBox.setItemText(2, _translate("WizardPage", "None"))
        self.vdw_modifierComboBox.setItemText(3, _translate("WizardPage", "Force-switch"))
        self.vdw_modifierComboBox.setItemText(4, _translate("WizardPage", "Potential-switch"))
        self.label_37.setText(_translate("WizardPage", "Cut-off distance for the short range VdW [nm]:"))
        self.label_38.setText(_translate("WizardPage", "Switching distance [nm]:"))
        self.label_39.setText(_translate("WizardPage", "Dispersion correction:"))
        self.dispcorrComboBox.setItemText(0, _translate("WizardPage", "no"))
        self.dispcorrComboBox.setItemText(1, _translate("WizardPage", "EnerPres"))
        self.dispcorrComboBox.setItemText(2, _translate("WizardPage", "Ener"))

