# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mdscripts/extract_energy.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_gmx_extract_energy(object):
    def setupUi(self, gmx_extract_energy):
        gmx_extract_energy.setObjectName("gmx_extract_energy")
        gmx_extract_energy.resize(1069, 635)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(gmx_extract_energy.sizePolicy().hasHeightForWidth())
        gmx_extract_energy.setSizePolicy(sizePolicy)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(gmx_extract_energy)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.splitter = QtWidgets.QSplitter(gmx_extract_energy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.toolBox = QtWidgets.QToolBox(self.splitter)
        self.toolBox.setObjectName("toolBox")
        self.pageOpenFile = QtWidgets.QWidget()
        self.pageOpenFile.setGeometry(QtCore.QRect(0, 0, 473, 555))
        self.pageOpenFile.setObjectName("pageOpenFile")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageOpenFile)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.treeViewOpenFile = QtWidgets.QTreeView(self.pageOpenFile)
        self.treeViewOpenFile.setObjectName("treeViewOpenFile")
        self.verticalLayout_3.addWidget(self.treeViewOpenFile)
        self.toolBox.addItem(self.pageOpenFile, "")
        self.pageCurves = QtWidgets.QWidget()
        self.pageCurves.setGeometry(QtCore.QRect(0, 0, 473, 555))
        self.pageCurves.setObjectName("pageCurves")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pageCurves)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeViewCurves = QtWidgets.QTreeView(self.pageCurves)
        self.treeViewCurves.setObjectName("treeViewCurves")
        self.verticalLayout_2.addWidget(self.treeViewCurves)
        self.widget_3 = QtWidgets.QWidget(self.pageCurves)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.hideAllPushButton = QtWidgets.QPushButton(self.widget_3)
        self.hideAllPushButton.setObjectName("hideAllPushButton")
        self.horizontalLayout_3.addWidget(self.hideAllPushButton)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.toolBox.addItem(self.pageCurves, "")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = QtWidgets.QWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tminSlider = QtWidgets.QSlider(self.widget_4)
        self.tminSlider.setOrientation(QtCore.Qt.Horizontal)
        self.tminSlider.setObjectName("tminSlider")
        self.gridLayout.addWidget(self.tminSlider, 0, 1, 1, 1)
        self.tminSpinBox = QtWidgets.QDoubleSpinBox(self.widget_4)
        self.tminSpinBox.setObjectName("tminSpinBox")
        self.gridLayout.addWidget(self.tminSpinBox, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.tmaxSlider = QtWidgets.QSlider(self.widget_4)
        self.tmaxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.tmaxSlider.setObjectName("tmaxSlider")
        self.gridLayout.addWidget(self.tmaxSlider, 1, 1, 1, 1)
        self.tmaxSpinBox = QtWidgets.QDoubleSpinBox(self.widget_4)
        self.tmaxSpinBox.setObjectName("tmaxSpinBox")
        self.gridLayout.addWidget(self.tmaxSpinBox, 1, 2, 1, 1)
        self.smoothingSlider = QtWidgets.QSlider(self.widget_4)
        self.smoothingSlider.setMaximum(100)
        self.smoothingSlider.setOrientation(QtCore.Qt.Horizontal)
        self.smoothingSlider.setObjectName("smoothingSlider")
        self.gridLayout.addWidget(self.smoothingSlider, 2, 1, 1, 1)
        self.smoothingSpinBox = QtWidgets.QSpinBox(self.widget_4)
        self.smoothingSpinBox.setObjectName("smoothingSpinBox")
        self.gridLayout.addWidget(self.smoothingSpinBox, 2, 2, 1, 1)
        self.smoothingFunctionComboBox = QtWidgets.QComboBox(self.widget_4)
        self.smoothingFunctionComboBox.setObjectName("smoothingFunctionComboBox")
        self.gridLayout.addWidget(self.smoothingFunctionComboBox, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_4)
        self.figureFrame = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.figureFrame.sizePolicy().hasHeightForWidth())
        self.figureFrame.setSizePolicy(sizePolicy)
        self.figureFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.figureFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.figureFrame.setObjectName("figureFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.figureFrame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayoutFigure = QtWidgets.QVBoxLayout()
        self.verticalLayoutFigure.setObjectName("verticalLayoutFigure")
        self.verticalLayout_5.addLayout(self.verticalLayoutFigure)
        self.verticalLayout.addWidget(self.figureFrame)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButtonGoFirst = QtWidgets.QToolButton(self.widget_2)
        icon = QtGui.QIcon.fromTheme("go-first")
        self.toolButtonGoFirst.setIcon(icon)
        self.toolButtonGoFirst.setObjectName("toolButtonGoFirst")
        self.horizontalLayout_2.addWidget(self.toolButtonGoFirst)
        self.toolButtonGoPrevious = QtWidgets.QToolButton(self.widget_2)
        icon = QtGui.QIcon.fromTheme("go-previous")
        self.toolButtonGoPrevious.setIcon(icon)
        self.toolButtonGoPrevious.setObjectName("toolButtonGoPrevious")
        self.horizontalLayout_2.addWidget(self.toolButtonGoPrevious)
        self.horizontalSliderCursor = QtWidgets.QSlider(self.widget_2)
        self.horizontalSliderCursor.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCursor.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSliderCursor.setObjectName("horizontalSliderCursor")
        self.horizontalLayout_2.addWidget(self.horizontalSliderCursor)
        self.toolButtonGoNext = QtWidgets.QToolButton(self.widget_2)
        icon = QtGui.QIcon.fromTheme("go-next")
        self.toolButtonGoNext.setIcon(icon)
        self.toolButtonGoNext.setObjectName("toolButtonGoNext")
        self.horizontalLayout_2.addWidget(self.toolButtonGoNext)
        self.toolButtonGoLast = QtWidgets.QToolButton(self.widget_2)
        icon = QtGui.QIcon.fromTheme("go-last")
        self.toolButtonGoLast.setIcon(icon)
        self.toolButtonGoLast.setObjectName("toolButtonGoLast")
        self.horizontalLayout_2.addWidget(self.toolButtonGoLast)
        self.verticalLayout.addWidget(self.widget_2)
        self.verticalLayout_6.addWidget(self.widget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.statisticsTreeView = QtWidgets.QTreeView(self.tab_2)
        self.statisticsTreeView.setAlternatingRowColors(True)
        self.statisticsTreeView.setObjectName("statisticsTreeView")
        self.verticalLayout_8.addWidget(self.statisticsTreeView)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_7.addWidget(self.splitter)

        self.retranslateUi(gmx_extract_energy)
        self.toolBox.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(gmx_extract_energy)

    def retranslateUi(self, gmx_extract_energy):
        _translate = QtCore.QCoreApplication.translate
        gmx_extract_energy.setWindowTitle(_translate("gmx_extract_energy", "gmx_extract_energy"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageOpenFile),
                                 _translate("gmx_extract_energy", "Open file..."))
        self.hideAllPushButton.setText(_translate("gmx_extract_energy", "Hide all"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageCurves), _translate("gmx_extract_energy", "Curves"))
        self.label.setText(_translate("gmx_extract_energy", "t_min for averaging:"))
        self.label_2.setText(_translate("gmx_extract_energy", "t_max for averaging:"))
        self.toolButtonGoFirst.setText(_translate("gmx_extract_energy", "..."))
        self.toolButtonGoPrevious.setText(_translate("gmx_extract_energy", "..."))
        self.toolButtonGoNext.setText(_translate("gmx_extract_energy", "..."))
        self.toolButtonGoLast.setText(_translate("gmx_extract_energy", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("gmx_extract_energy", "Graph"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("gmx_extract_energy", "Statistics"))

