# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/mdscripts/mdpmaker/mdpmaker.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName("Wizard")
        Wizard.resize(650, 515)
        Wizard.setSizeGripEnabled(True)
        Wizard.setWizardStyle(QtWidgets.QWizard.ClassicStyle)
        Wizard.setOptions(QtWidgets.QWizard.HaveCustomButton1|QtWidgets.QWizard.NoBackButtonOnStartPage)
        self.introWizardPage = WPIntro()
        self.introWizardPage.setObjectName("introWizardPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.introWizardPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.introWizardPage)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.consentCheckBox = QtWidgets.QCheckBox(self.introWizardPage)
        self.consentCheckBox.setObjectName("consentCheckBox")
        self.verticalLayout.addWidget(self.consentCheckBox)
        Wizard.addPage(self.introWizardPage)
        self.simTypeWizardPage = WPIntro()
        self.simTypeWizardPage.setObjectName("simTypeWizardPage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.simTypeWizardPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.typeEnergyMinimizationRadioButton = QtWidgets.QRadioButton(self.simTypeWizardPage)
        self.typeEnergyMinimizationRadioButton.setChecked(True)
        self.typeEnergyMinimizationRadioButton.setObjectName("typeEnergyMinimizationRadioButton")
        self.verticalLayout_2.addWidget(self.typeEnergyMinimizationRadioButton)
        self.typeNVTRadioButton = QtWidgets.QRadioButton(self.simTypeWizardPage)
        self.typeNVTRadioButton.setObjectName("typeNVTRadioButton")
        self.verticalLayout_2.addWidget(self.typeNVTRadioButton)
        self.typeNPTRadioButton = QtWidgets.QRadioButton(self.simTypeWizardPage)
        self.typeNPTRadioButton.setObjectName("typeNPTRadioButton")
        self.verticalLayout_2.addWidget(self.typeNPTRadioButton)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.simTypeWizardPage)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.timeUnitComboBox = QtWidgets.QComboBox(self.simTypeWizardPage)
        self.timeUnitComboBox.setObjectName("timeUnitComboBox")
        self.timeUnitComboBox.addItem("")
        self.timeUnitComboBox.addItem("")
        self.timeUnitComboBox.addItem("")
        self.timeUnitComboBox.addItem("")
        self.horizontalLayout.addWidget(self.timeUnitComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        Wizard.addPage(self.simTypeWizardPage)
        self.emWizardPage = QtWidgets.QWizardPage()
        self.emWizardPage.setObjectName("emWizardPage")
        self.gridLayout = QtWidgets.QGridLayout(self.emWizardPage)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.emWizardPage)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.emWizardPage)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.emnstcgsteepSpinBox = QtWidgets.QSpinBox(self.emWizardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emnstcgsteepSpinBox.sizePolicy().hasHeightForWidth())
        self.emnstcgsteepSpinBox.setSizePolicy(sizePolicy)
        self.emnstcgsteepSpinBox.setMinimum(0)
        self.emnstcgsteepSpinBox.setMaximum(999999)
        self.emnstcgsteepSpinBox.setProperty("value", 1000)
        self.emnstcgsteepSpinBox.setObjectName("emnstcgsteepSpinBox")
        self.gridLayout.addWidget(self.emnstcgsteepSpinBox, 3, 1, 1, 1)
        self.emToleranceDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.emWizardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emToleranceDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.emToleranceDoubleSpinBox.setSizePolicy(sizePolicy)
        self.emToleranceDoubleSpinBox.setDecimals(4)
        self.emToleranceDoubleSpinBox.setMaximum(999.0)
        self.emToleranceDoubleSpinBox.setProperty("value", 10.0)
        self.emToleranceDoubleSpinBox.setObjectName("emToleranceDoubleSpinBox")
        self.gridLayout.addWidget(self.emToleranceDoubleSpinBox, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.emWizardPage)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.emIntegratorComboBox = QtWidgets.QComboBox(self.emWizardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emIntegratorComboBox.sizePolicy().hasHeightForWidth())
        self.emIntegratorComboBox.setSizePolicy(sizePolicy)
        self.emIntegratorComboBox.setObjectName("emIntegratorComboBox")
        self.emIntegratorComboBox.addItem("")
        self.emIntegratorComboBox.addItem("")
        self.emIntegratorComboBox.addItem("")
        self.gridLayout.addWidget(self.emIntegratorComboBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.emWizardPage)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.emWizardPage)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.emnbfgscorrSpinBox = QtWidgets.QSpinBox(self.emWizardPage)
        self.emnbfgscorrSpinBox.setMaximum(9999999)
        self.emnbfgscorrSpinBox.setProperty("value", 10)
        self.emnbfgscorrSpinBox.setObjectName("emnbfgscorrSpinBox")
        self.gridLayout.addWidget(self.emnbfgscorrSpinBox, 4, 1, 1, 1)
        self.emInitialStepSizeDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.emWizardPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emInitialStepSizeDoubleSpinBox.sizePolicy().hasHeightForWidth())
        self.emInitialStepSizeDoubleSpinBox.setSizePolicy(sizePolicy)
        self.emInitialStepSizeDoubleSpinBox.setDecimals(4)
        self.emInitialStepSizeDoubleSpinBox.setProperty("value", 0.01)
        self.emInitialStepSizeDoubleSpinBox.setObjectName("emInitialStepSizeDoubleSpinBox")
        self.gridLayout.addWidget(self.emInitialStepSizeDoubleSpinBox, 2, 1, 1, 1)
        self.emNstepsSpinBox = QtWidgets.QSpinBox(self.emWizardPage)
        self.emNstepsSpinBox.setMinimum(-1)
        self.emNstepsSpinBox.setMaximum(999999999)
        self.emNstepsSpinBox.setProperty("value", 0)
        self.emNstepsSpinBox.setObjectName("emNstepsSpinBox")
        self.gridLayout.addWidget(self.emNstepsSpinBox, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.emWizardPage)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        Wizard.addPage(self.emWizardPage)
        self.integratorWizardPage = QtWidgets.QWizardPage()
        self.integratorWizardPage.setObjectName("integratorWizardPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.integratorWizardPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.integratorWizardPage)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.nstepsSpinBox = QtWidgets.QSpinBox(self.integratorWizardPage)
        self.nstepsSpinBox.setMaximum(999999999)
        self.nstepsSpinBox.setObjectName("nstepsSpinBox")
        self.gridLayout_2.addWidget(self.nstepsSpinBox, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.integratorWizardPage)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.nstcommSpinBox = QtWidgets.QSpinBox(self.integratorWizardPage)
        self.nstcommSpinBox.setMaximum(999999999)
        self.nstcommSpinBox.setObjectName("nstcommSpinBox")
        self.gridLayout_2.addWidget(self.nstcommSpinBox, 4, 1, 1, 1)
        self.commGrpsLineEdit = QtWidgets.QLineEdit(self.integratorWizardPage)
        self.commGrpsLineEdit.setObjectName("commGrpsLineEdit")
        self.gridLayout_2.addWidget(self.commGrpsLineEdit, 5, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.integratorWizardPage)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.integratorWizardPage)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 5, 0, 1, 1)
        self.timeStepDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.integratorWizardPage)
        self.timeStepDoubleSpinBox.setDecimals(10)
        self.timeStepDoubleSpinBox.setMaximum(99999999.0)
        self.timeStepDoubleSpinBox.setProperty("value", 0.002)
        self.timeStepDoubleSpinBox.setObjectName("timeStepDoubleSpinBox")
        self.gridLayout_2.addWidget(self.timeStepDoubleSpinBox, 1, 1, 1, 1)
        self.commTypeComboBox = QtWidgets.QComboBox(self.integratorWizardPage)
        self.commTypeComboBox.setObjectName("commTypeComboBox")
        self.commTypeComboBox.addItem("")
        self.commTypeComboBox.addItem("")
        self.commTypeComboBox.addItem("")
        self.commTypeComboBox.addItem("")
        self.gridLayout_2.addWidget(self.commTypeComboBox, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.integratorWizardPage)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.nstepsTimeLabel = QtWidgets.QLabel(self.integratorWizardPage)
        self.nstepsTimeLabel.setObjectName("nstepsTimeLabel")
        self.gridLayout_2.addWidget(self.nstepsTimeLabel, 2, 2, 1, 1)
        self.nstcommTimeLabel = QtWidgets.QLabel(self.integratorWizardPage)
        self.nstcommTimeLabel.setObjectName("nstcommTimeLabel")
        self.gridLayout_2.addWidget(self.nstcommTimeLabel, 4, 2, 1, 1)
        Wizard.addPage(self.integratorWizardPage)
        self.outputWizardPage = QtWidgets.QWizardPage()
        self.outputWizardPage.setObjectName("outputWizardPage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.outputWizardPage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.compressed_x_precisionDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.outputWizardPage)
        self.compressed_x_precisionDoubleSpinBox.setMaximum(9999999.0)
        self.compressed_x_precisionDoubleSpinBox.setProperty("value", 1000.0)
        self.compressed_x_precisionDoubleSpinBox.setObjectName("compressed_x_precisionDoubleSpinBox")
        self.gridLayout_3.addWidget(self.compressed_x_precisionDoubleSpinBox, 7, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.outputWizardPage)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 4, 0, 1, 1)
        self.nstlogSpinBox = QtWidgets.QSpinBox(self.outputWizardPage)
        self.nstlogSpinBox.setMaximum(999999999)
        self.nstlogSpinBox.setProperty("value", 1000)
        self.nstlogSpinBox.setObjectName("nstlogSpinBox")
        self.gridLayout_3.addWidget(self.nstlogSpinBox, 3, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.outputWizardPage)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 6, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.outputWizardPage)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 5, 0, 1, 1)
        self.nstxoutSpinBox = QtWidgets.QSpinBox(self.outputWizardPage)
        self.nstxoutSpinBox.setMaximum(999999999)
        self.nstxoutSpinBox.setObjectName("nstxoutSpinBox")
        self.gridLayout_3.addWidget(self.nstxoutSpinBox, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.outputWizardPage)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 0, 1, 1)
        self.nstxout_copressedSpinBox = QtWidgets.QSpinBox(self.outputWizardPage)
        self.nstxout_copressedSpinBox.setMaximum(999999999)
        self.nstxout_copressedSpinBox.setObjectName("nstxout_copressedSpinBox")
        self.gridLayout_3.addWidget(self.nstxout_copressedSpinBox, 6, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.outputWizardPage)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 3, 0, 1, 1)
        self.nstfoutSpinBox = QtWidgets.QSpinBox(self.outputWizardPage)
        self.nstfoutSpinBox.setMaximum(999999999)
        self.nstfoutSpinBox.setObjectName("nstfoutSpinBox")
        self.gridLayout_3.addWidget(self.nstfoutSpinBox, 2, 1, 1, 1)
        self.nstenergySpinBox = QtWidgets.QSpinBox(self.outputWizardPage)
        self.nstenergySpinBox.setMaximum(999999999)
        self.nstenergySpinBox.setProperty("value", 1000)
        self.nstenergySpinBox.setObjectName("nstenergySpinBox")
        self.gridLayout_3.addWidget(self.nstenergySpinBox, 4, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.outputWizardPage)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 2, 0, 1, 1)
        self.nstcalcenergySpinBox = QtWidgets.QSpinBox(self.outputWizardPage)
        self.nstcalcenergySpinBox.setMaximum(999999999)
        self.nstcalcenergySpinBox.setProperty("value", 100)
        self.nstcalcenergySpinBox.setObjectName("nstcalcenergySpinBox")
        self.gridLayout_3.addWidget(self.nstcalcenergySpinBox, 5, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.outputWizardPage)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 7, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.outputWizardPage)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 8, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.outputWizardPage)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 0, 1, 1)
        self.nstvoutSpinBox = QtWidgets.QSpinBox(self.outputWizardPage)
        self.nstvoutSpinBox.setMaximum(999999999)
        self.nstvoutSpinBox.setObjectName("nstvoutSpinBox")
        self.gridLayout_3.addWidget(self.nstvoutSpinBox, 1, 1, 1, 1)
        self.nstxoutTimeLabel = QtWidgets.QLabel(self.outputWizardPage)
        self.nstxoutTimeLabel.setObjectName("nstxoutTimeLabel")
        self.gridLayout_3.addWidget(self.nstxoutTimeLabel, 0, 2, 1, 1)
        self.nstvoutTimeLabel = QtWidgets.QLabel(self.outputWizardPage)
        self.nstvoutTimeLabel.setObjectName("nstvoutTimeLabel")
        self.gridLayout_3.addWidget(self.nstvoutTimeLabel, 1, 2, 1, 1)
        self.nstfoutTimeLabel = QtWidgets.QLabel(self.outputWizardPage)
        self.nstfoutTimeLabel.setObjectName("nstfoutTimeLabel")
        self.gridLayout_3.addWidget(self.nstfoutTimeLabel, 2, 2, 1, 1)
        self.nstlogTimeLabel = QtWidgets.QLabel(self.outputWizardPage)
        self.nstlogTimeLabel.setObjectName("nstlogTimeLabel")
        self.gridLayout_3.addWidget(self.nstlogTimeLabel, 3, 2, 1, 1)
        self.nstenergyTimeLabel = QtWidgets.QLabel(self.outputWizardPage)
        self.nstenergyTimeLabel.setObjectName("nstenergyTimeLabel")
        self.gridLayout_3.addWidget(self.nstenergyTimeLabel, 4, 2, 1, 1)
        self.nstcalcenergyTimeLabel = QtWidgets.QLabel(self.outputWizardPage)
        self.nstcalcenergyTimeLabel.setObjectName("nstcalcenergyTimeLabel")
        self.gridLayout_3.addWidget(self.nstcalcenergyTimeLabel, 5, 2, 1, 1)
        self.nstxout_compressedTimeLabel = QtWidgets.QLabel(self.outputWizardPage)
        self.nstxout_compressedTimeLabel.setObjectName("nstxout_compressedTimeLabel")
        self.gridLayout_3.addWidget(self.nstxout_compressedTimeLabel, 6, 2, 1, 1)
        self.compressed_x_grpsLineEdit = QtWidgets.QLineEdit(self.outputWizardPage)
        self.compressed_x_grpsLineEdit.setObjectName("compressed_x_grpsLineEdit")
        self.gridLayout_3.addWidget(self.compressed_x_grpsLineEdit, 8, 1, 1, 1)
        Wizard.addPage(self.outputWizardPage)
        self.neighbourSearchWizardPage = QtWidgets.QWizardPage()
        self.neighbourSearchWizardPage.setObjectName("neighbourSearchWizardPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.neighbourSearchWizardPage)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verlet_buffer_toleranceDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.neighbourSearchWizardPage)
        self.verlet_buffer_toleranceDoubleSpinBox.setDecimals(6)
        self.verlet_buffer_toleranceDoubleSpinBox.setMaximum(999999999999.0)
        self.verlet_buffer_toleranceDoubleSpinBox.setProperty("value", 0.005)
        self.verlet_buffer_toleranceDoubleSpinBox.setObjectName("verlet_buffer_toleranceDoubleSpinBox")
        self.gridLayout_4.addWidget(self.verlet_buffer_toleranceDoubleSpinBox, 4, 1, 1, 1)
        self.pbcComboBox = QtWidgets.QComboBox(self.neighbourSearchWizardPage)
        self.pbcComboBox.setObjectName("pbcComboBox")
        self.pbcComboBox.addItem("")
        self.pbcComboBox.addItem("")
        self.pbcComboBox.addItem("")
        self.gridLayout_4.addWidget(self.pbcComboBox, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.neighbourSearchWizardPage)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 1, 0, 1, 1)
        self.nstlistSpinBox = QtWidgets.QSpinBox(self.neighbourSearchWizardPage)
        self.nstlistSpinBox.setObjectName("nstlistSpinBox")
        self.gridLayout_4.addWidget(self.nstlistSpinBox, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.neighbourSearchWizardPage)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.neighbourSearchWizardPage)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.neighbourSearchWizardPage)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 3, 0, 1, 1)
        self.ns_typeComboBox = QtWidgets.QComboBox(self.neighbourSearchWizardPage)
        self.ns_typeComboBox.setObjectName("ns_typeComboBox")
        self.ns_typeComboBox.addItem("")
        self.ns_typeComboBox.addItem("")
        self.gridLayout_4.addWidget(self.ns_typeComboBox, 2, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.neighbourSearchWizardPage)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 4, 0, 1, 1)
        self.cutoff_schemeComboBox = QtWidgets.QComboBox(self.neighbourSearchWizardPage)
        self.cutoff_schemeComboBox.setObjectName("cutoff_schemeComboBox")
        self.cutoff_schemeComboBox.addItem("")
        self.cutoff_schemeComboBox.addItem("")
        self.gridLayout_4.addWidget(self.cutoff_schemeComboBox, 0, 1, 1, 1)
        self.nstListTimeLabel = QtWidgets.QLabel(self.neighbourSearchWizardPage)
        self.nstListTimeLabel.setObjectName("nstListTimeLabel")
        self.gridLayout_4.addWidget(self.nstListTimeLabel, 1, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.neighbourSearchWizardPage)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 5, 0, 1, 1)
        self.rlistDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.neighbourSearchWizardPage)
        self.rlistDoubleSpinBox.setDecimals(4)
        self.rlistDoubleSpinBox.setMaximum(999999999999.0)
        self.rlistDoubleSpinBox.setProperty("value", 0.01)
        self.rlistDoubleSpinBox.setObjectName("rlistDoubleSpinBox")
        self.gridLayout_4.addWidget(self.rlistDoubleSpinBox, 5, 1, 1, 1)
        Wizard.addPage(self.neighbourSearchWizardPage)
        self.coulombWizardPage = QtWidgets.QWizardPage()
        self.coulombWizardPage.setObjectName("coulombWizardPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.coulombWizardPage)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_33 = QtWidgets.QLabel(self.coulombWizardPage)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 4, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.coulombWizardPage)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 1, 0, 1, 1)
        self.coulomb_modifierComboBox = QtWidgets.QComboBox(self.coulombWizardPage)
        self.coulomb_modifierComboBox.setObjectName("coulomb_modifierComboBox")
        self.coulomb_modifierComboBox.addItem("")
        self.coulomb_modifierComboBox.addItem("")
        self.coulomb_modifierComboBox.addItem("")
        self.gridLayout_5.addWidget(self.coulomb_modifierComboBox, 1, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.coulombWizardPage)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 2, 0, 1, 1)
        self.coulombtypeComboBox = QtWidgets.QComboBox(self.coulombWizardPage)
        self.coulombtypeComboBox.setObjectName("coulombtypeComboBox")
        self.coulombtypeComboBox.addItem("")
        self.coulombtypeComboBox.addItem("")
        self.coulombtypeComboBox.addItem("")
        self.coulombtypeComboBox.addItem("")
        self.coulombtypeComboBox.addItem("")
        self.coulombtypeComboBox.addItem("")
        self.gridLayout_5.addWidget(self.coulombtypeComboBox, 0, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.coulombWizardPage)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 0, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.coulombWizardPage)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 3, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.coulombWizardPage)
        self.label_34.setObjectName("label_34")
        self.gridLayout_5.addWidget(self.label_34, 5, 0, 1, 1)
        self.rcoulomb_switchDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.coulombWizardPage)
        self.rcoulomb_switchDoubleSpinBox.setDecimals(4)
        self.rcoulomb_switchDoubleSpinBox.setMaximum(999999.0)
        self.rcoulomb_switchDoubleSpinBox.setObjectName("rcoulomb_switchDoubleSpinBox")
        self.gridLayout_5.addWidget(self.rcoulomb_switchDoubleSpinBox, 2, 1, 1, 1)
        self.rcoulombDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.coulombWizardPage)
        self.rcoulombDoubleSpinBox.setMaximum(99999999999.0)
        self.rcoulombDoubleSpinBox.setProperty("value", 1.0)
        self.rcoulombDoubleSpinBox.setObjectName("rcoulombDoubleSpinBox")
        self.gridLayout_5.addWidget(self.rcoulombDoubleSpinBox, 3, 1, 1, 1)
        self.epsilon_rDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.coulombWizardPage)
        self.epsilon_rDoubleSpinBox.setDecimals(4)
        self.epsilon_rDoubleSpinBox.setMaximum(99999999999.0)
        self.epsilon_rDoubleSpinBox.setProperty("value", 1.0)
        self.epsilon_rDoubleSpinBox.setObjectName("epsilon_rDoubleSpinBox")
        self.gridLayout_5.addWidget(self.epsilon_rDoubleSpinBox, 4, 1, 1, 1)
        self.epsilon_rfDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.coulombWizardPage)
        self.epsilon_rfDoubleSpinBox.setDecimals(4)
        self.epsilon_rfDoubleSpinBox.setMaximum(9999999999999.0)
        self.epsilon_rfDoubleSpinBox.setObjectName("epsilon_rfDoubleSpinBox")
        self.gridLayout_5.addWidget(self.epsilon_rfDoubleSpinBox, 5, 1, 1, 1)
        Wizard.addPage(self.coulombWizardPage)
        self.vdwWizardPage = QtWidgets.QWizardPage()
        self.vdwWizardPage.setObjectName("vdwWizardPage")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.vdwWizardPage)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_38 = QtWidgets.QLabel(self.vdwWizardPage)
        self.label_38.setObjectName("label_38")
        self.gridLayout_6.addWidget(self.label_38, 3, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.vdwWizardPage)
        self.label_35.setObjectName("label_35")
        self.gridLayout_6.addWidget(self.label_35, 0, 0, 1, 1)
        self.vdwtypeComboBox = QtWidgets.QComboBox(self.vdwWizardPage)
        self.vdwtypeComboBox.setObjectName("vdwtypeComboBox")
        self.vdwtypeComboBox.addItem("")
        self.vdwtypeComboBox.addItem("")
        self.vdwtypeComboBox.addItem("")
        self.vdwtypeComboBox.addItem("")
        self.gridLayout_6.addWidget(self.vdwtypeComboBox, 0, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.vdwWizardPage)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 1, 0, 1, 1)
        self.vdw_modifierComboBox = QtWidgets.QComboBox(self.vdwWizardPage)
        self.vdw_modifierComboBox.setObjectName("vdw_modifierComboBox")
        self.vdw_modifierComboBox.addItem("")
        self.vdw_modifierComboBox.addItem("")
        self.vdw_modifierComboBox.addItem("")
        self.vdw_modifierComboBox.addItem("")
        self.vdw_modifierComboBox.addItem("")
        self.gridLayout_6.addWidget(self.vdw_modifierComboBox, 1, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.vdwWizardPage)
        self.label_37.setObjectName("label_37")
        self.gridLayout_6.addWidget(self.label_37, 2, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.vdwWizardPage)
        self.label_39.setObjectName("label_39")
        self.gridLayout_6.addWidget(self.label_39, 4, 0, 1, 1)
        self.dispcorrComboBox = QtWidgets.QComboBox(self.vdwWizardPage)
        self.dispcorrComboBox.setObjectName("dispcorrComboBox")
        self.dispcorrComboBox.addItem("")
        self.dispcorrComboBox.addItem("")
        self.dispcorrComboBox.addItem("")
        self.gridLayout_6.addWidget(self.dispcorrComboBox, 4, 1, 1, 1)
        self.rvdwDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.vdwWizardPage)
        self.rvdwDoubleSpinBox.setDecimals(4)
        self.rvdwDoubleSpinBox.setMaximum(99999999.0)
        self.rvdwDoubleSpinBox.setProperty("value", 1.0)
        self.rvdwDoubleSpinBox.setObjectName("rvdwDoubleSpinBox")
        self.gridLayout_6.addWidget(self.rvdwDoubleSpinBox, 2, 1, 1, 1)
        self.rvdw_switchDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.vdwWizardPage)
        self.rvdw_switchDoubleSpinBox.setMaximum(9999999999.0)
        self.rvdw_switchDoubleSpinBox.setObjectName("rvdw_switchDoubleSpinBox")
        self.gridLayout_6.addWidget(self.rvdw_switchDoubleSpinBox, 3, 1, 1, 1)
        Wizard.addPage(self.vdwWizardPage)
        self.ewaldWizardPage = QtWidgets.QWizardPage()
        self.ewaldWizardPage.setObjectName("ewaldWizardPage")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.ewaldWizardPage)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_57 = QtWidgets.QLabel(self.ewaldWizardPage)
        self.label_57.setObjectName("label_57")
        self.gridLayout_7.addWidget(self.label_57, 4, 0, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.ewaldWizardPage)
        self.label_59.setObjectName("label_59")
        self.gridLayout_7.addWidget(self.label_59, 5, 0, 1, 1)
        self.pme_orderSpinBox = QtWidgets.QSpinBox(self.ewaldWizardPage)
        self.pme_orderSpinBox.setProperty("value", 4)
        self.pme_orderSpinBox.setObjectName("pme_orderSpinBox")
        self.gridLayout_7.addWidget(self.pme_orderSpinBox, 1, 1, 1, 1)
        self.constraintsComboBox = QtWidgets.QComboBox(self.ewaldWizardPage)
        self.constraintsComboBox.setObjectName("constraintsComboBox")
        self.constraintsComboBox.addItem("")
        self.constraintsComboBox.addItem("")
        self.constraintsComboBox.addItem("")
        self.constraintsComboBox.addItem("")
        self.constraintsComboBox.addItem("")
        self.gridLayout_7.addWidget(self.constraintsComboBox, 3, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.ewaldWizardPage)
        self.label_58.setObjectName("label_58")
        self.gridLayout_7.addWidget(self.label_58, 4, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.ewaldWizardPage)
        self.label_40.setObjectName("label_40")
        self.gridLayout_7.addWidget(self.label_40, 0, 0, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.ewaldWizardPage)
        self.label_60.setObjectName("label_60")
        self.gridLayout_7.addWidget(self.label_60, 6, 0, 1, 1)
        self.fourierspacingDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.ewaldWizardPage)
        self.fourierspacingDoubleSpinBox.setDecimals(4)
        self.fourierspacingDoubleSpinBox.setMaximum(999999999.0)
        self.fourierspacingDoubleSpinBox.setProperty("value", 0.12)
        self.fourierspacingDoubleSpinBox.setObjectName("fourierspacingDoubleSpinBox")
        self.gridLayout_7.addWidget(self.fourierspacingDoubleSpinBox, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.ewaldWizardPage)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_7.addWidget(self.line, 2, 0, 1, 2)
        self.label_56 = QtWidgets.QLabel(self.ewaldWizardPage)
        self.label_56.setObjectName("label_56")
        self.gridLayout_7.addWidget(self.label_56, 3, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.ewaldWizardPage)
        self.label_41.setObjectName("label_41")
        self.gridLayout_7.addWidget(self.label_41, 1, 0, 1, 1)
        self.lincs_orderSpinBox = QtWidgets.QSpinBox(self.ewaldWizardPage)
        self.lincs_orderSpinBox.setProperty("value", 4)
        self.lincs_orderSpinBox.setObjectName("lincs_orderSpinBox")
        self.gridLayout_7.addWidget(self.lincs_orderSpinBox, 5, 1, 1, 1)
        self.lincs_iterSpinBox = QtWidgets.QSpinBox(self.ewaldWizardPage)
        self.lincs_iterSpinBox.setMinimum(1)
        self.lincs_iterSpinBox.setObjectName("lincs_iterSpinBox")
        self.gridLayout_7.addWidget(self.lincs_iterSpinBox, 6, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.ewaldWizardPage)
        self.label_61.setObjectName("label_61")
        self.gridLayout_7.addWidget(self.label_61, 7, 0, 1, 1)
        self.lincs_warnangleDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.ewaldWizardPage)
        self.lincs_warnangleDoubleSpinBox.setMaximum(360.0)
        self.lincs_warnangleDoubleSpinBox.setProperty("value", 30.0)
        self.lincs_warnangleDoubleSpinBox.setObjectName("lincs_warnangleDoubleSpinBox")
        self.gridLayout_7.addWidget(self.lincs_warnangleDoubleSpinBox, 7, 1, 1, 1)
        Wizard.addPage(self.ewaldWizardPage)
        self.tcouplWizardPage = QtWidgets.QWizardPage()
        self.tcouplWizardPage.setObjectName("tcouplWizardPage")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tcouplWizardPage)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.nsttcoupleTimeLabel = QtWidgets.QLabel(self.tcouplWizardPage)
        self.nsttcoupleTimeLabel.setObjectName("nsttcoupleTimeLabel")
        self.gridLayout_8.addWidget(self.nsttcoupleTimeLabel, 1, 2, 1, 1)
        self.tau_tDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.tcouplWizardPage)
        self.tau_tDoubleSpinBox.setDecimals(4)
        self.tau_tDoubleSpinBox.setMaximum(999999999999.0)
        self.tau_tDoubleSpinBox.setProperty("value", 1.0)
        self.tau_tDoubleSpinBox.setObjectName("tau_tDoubleSpinBox")
        self.gridLayout_8.addWidget(self.tau_tDoubleSpinBox, 4, 1, 1, 2)
        self.tc_grpsLineEdit = QtWidgets.QLineEdit(self.tcouplWizardPage)
        self.tc_grpsLineEdit.setObjectName("tc_grpsLineEdit")
        self.gridLayout_8.addWidget(self.tc_grpsLineEdit, 2, 1, 1, 2)
        self.nsttcoupleSpinBox = QtWidgets.QSpinBox(self.tcouplWizardPage)
        self.nsttcoupleSpinBox.setMinimum(-1)
        self.nsttcoupleSpinBox.setProperty("value", -1)
        self.nsttcoupleSpinBox.setObjectName("nsttcoupleSpinBox")
        self.gridLayout_8.addWidget(self.nsttcoupleSpinBox, 1, 1, 1, 1)
        self.ref_tDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.tcouplWizardPage)
        self.ref_tDoubleSpinBox.setDecimals(4)
        self.ref_tDoubleSpinBox.setMaximum(9999999.0)
        self.ref_tDoubleSpinBox.setProperty("value", 300.0)
        self.ref_tDoubleSpinBox.setObjectName("ref_tDoubleSpinBox")
        self.gridLayout_8.addWidget(self.ref_tDoubleSpinBox, 3, 1, 1, 2)
        self.label_42 = QtWidgets.QLabel(self.tcouplWizardPage)
        self.label_42.setObjectName("label_42")
        self.gridLayout_8.addWidget(self.label_42, 0, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.tcouplWizardPage)
        self.label_46.setObjectName("label_46")
        self.gridLayout_8.addWidget(self.label_46, 3, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.tcouplWizardPage)
        self.label_47.setObjectName("label_47")
        self.gridLayout_8.addWidget(self.label_47, 4, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.tcouplWizardPage)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 1, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.tcouplWizardPage)
        self.label_45.setObjectName("label_45")
        self.gridLayout_8.addWidget(self.label_45, 2, 0, 1, 1)
        self.tcouplComboBox = QtWidgets.QComboBox(self.tcouplWizardPage)
        self.tcouplComboBox.setObjectName("tcouplComboBox")
        self.tcouplComboBox.addItem("")
        self.tcouplComboBox.addItem("")
        self.tcouplComboBox.addItem("")
        self.gridLayout_8.addWidget(self.tcouplComboBox, 0, 1, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.tcouplWizardPage)
        self.groupBox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_44 = QtWidgets.QLabel(self.groupBox)
        self.label_44.setObjectName("label_44")
        self.gridLayout_9.addWidget(self.label_44, 0, 0, 1, 1)
        self.gen_tempDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.gen_tempDoubleSpinBox.setDecimals(4)
        self.gen_tempDoubleSpinBox.setMaximum(99999999999.0)
        self.gen_tempDoubleSpinBox.setProperty("value", 300.0)
        self.gen_tempDoubleSpinBox.setObjectName("gen_tempDoubleSpinBox")
        self.gridLayout_9.addWidget(self.gen_tempDoubleSpinBox, 0, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBox)
        self.label_48.setObjectName("label_48")
        self.gridLayout_9.addWidget(self.label_48, 1, 0, 1, 1)
        self.gen_seedSpinBox = QtWidgets.QSpinBox(self.groupBox)
        self.gen_seedSpinBox.setMinimum(-1)
        self.gen_seedSpinBox.setMaximum(999999999)
        self.gen_seedSpinBox.setProperty("value", -1)
        self.gen_seedSpinBox.setObjectName("gen_seedSpinBox")
        self.gridLayout_9.addWidget(self.gen_seedSpinBox, 1, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox, 5, 0, 1, 3)
        Wizard.addPage(self.tcouplWizardPage)
        self.pcouplWizardPage = QtWidgets.QWizardPage()
        self.pcouplWizardPage.setObjectName("pcouplWizardPage")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.pcouplWizardPage)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_49 = QtWidgets.QLabel(self.pcouplWizardPage)
        self.label_49.setObjectName("label_49")
        self.gridLayout_10.addWidget(self.label_49, 0, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.pcouplWizardPage)
        self.label_50.setObjectName("label_50")
        self.gridLayout_10.addWidget(self.label_50, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nstpcoupleSpinBox = QtWidgets.QSpinBox(self.pcouplWizardPage)
        self.nstpcoupleSpinBox.setMinimum(-1)
        self.nstpcoupleSpinBox.setMaximum(99999999)
        self.nstpcoupleSpinBox.setProperty("value", -1)
        self.nstpcoupleSpinBox.setObjectName("nstpcoupleSpinBox")
        self.horizontalLayout_2.addWidget(self.nstpcoupleSpinBox)
        self.nstpcoupleTimeLabel = QtWidgets.QLabel(self.pcouplWizardPage)
        self.nstpcoupleTimeLabel.setObjectName("nstpcoupleTimeLabel")
        self.horizontalLayout_2.addWidget(self.nstpcoupleTimeLabel)
        self.gridLayout_10.addLayout(self.horizontalLayout_2, 2, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ref_pDoubleSpinbox_1 = QtWidgets.QDoubleSpinBox(self.pcouplWizardPage)
        self.ref_pDoubleSpinbox_1.setObjectName("ref_pDoubleSpinbox_1")
        self.horizontalLayout_4.addWidget(self.ref_pDoubleSpinbox_1)
        self.ref_pDoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.pcouplWizardPage)
        self.ref_pDoubleSpinBox_2.setObjectName("ref_pDoubleSpinBox_2")
        self.horizontalLayout_4.addWidget(self.ref_pDoubleSpinBox_2)
        self.gridLayout_10.addLayout(self.horizontalLayout_4, 5, 1, 1, 1)
        self.pcopultypeComboBox = QtWidgets.QComboBox(self.pcouplWizardPage)
        self.pcopultypeComboBox.setObjectName("pcopultypeComboBox")
        self.pcopultypeComboBox.addItem("")
        self.pcopultypeComboBox.addItem("")
        self.pcopultypeComboBox.addItem("")
        self.gridLayout_10.addWidget(self.pcopultypeComboBox, 1, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.pcouplWizardPage)
        self.label_54.setObjectName("label_54")
        self.gridLayout_10.addWidget(self.label_54, 5, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.pcouplWizardPage)
        self.label_52.setObjectName("label_52")
        self.gridLayout_10.addWidget(self.label_52, 3, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.pcouplWizardPage)
        self.label_51.setObjectName("label_51")
        self.gridLayout_10.addWidget(self.label_51, 2, 0, 1, 1)
        self.tau_pDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.pcouplWizardPage)
        self.tau_pDoubleSpinBox.setDecimals(4)
        self.tau_pDoubleSpinBox.setMaximum(9999999.0)
        self.tau_pDoubleSpinBox.setProperty("value", 1.0)
        self.tau_pDoubleSpinBox.setObjectName("tau_pDoubleSpinBox")
        self.gridLayout_10.addWidget(self.tau_pDoubleSpinBox, 3, 1, 1, 1)
        self.pcouplComboBox = QtWidgets.QComboBox(self.pcouplWizardPage)
        self.pcouplComboBox.setObjectName("pcouplComboBox")
        self.pcouplComboBox.addItem("")
        self.pcouplComboBox.addItem("")
        self.gridLayout_10.addWidget(self.pcouplComboBox, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.compressibilityDoubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.pcouplWizardPage)
        self.compressibilityDoubleSpinBox_1.setObjectName("compressibilityDoubleSpinBox_1")
        self.horizontalLayout_3.addWidget(self.compressibilityDoubleSpinBox_1)
        self.compressibilityDoubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.pcouplWizardPage)
        self.compressibilityDoubleSpinBox_2.setObjectName("compressibilityDoubleSpinBox_2")
        self.horizontalLayout_3.addWidget(self.compressibilityDoubleSpinBox_2)
        self.gridLayout_10.addLayout(self.horizontalLayout_3, 4, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.pcouplWizardPage)
        self.label_53.setObjectName("label_53")
        self.gridLayout_10.addWidget(self.label_53, 4, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.pcouplWizardPage)
        self.label_55.setObjectName("label_55")
        self.gridLayout_10.addWidget(self.label_55, 6, 0, 1, 1)
        self.refcoord_scalingComboBox = QtWidgets.QComboBox(self.pcouplWizardPage)
        self.refcoord_scalingComboBox.setObjectName("refcoord_scalingComboBox")
        self.refcoord_scalingComboBox.addItem("")
        self.refcoord_scalingComboBox.addItem("")
        self.refcoord_scalingComboBox.addItem("")
        self.gridLayout_10.addWidget(self.refcoord_scalingComboBox, 6, 1, 1, 1)
        Wizard.addPage(self.pcouplWizardPage)
        self.endWizardPage = QtWidgets.QWizardPage()
        self.endWizardPage.setObjectName("endWizardPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.endWizardPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        Wizard.addPage(self.endWizardPage)

        self.retranslateUi(Wizard)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        _translate = QtCore.QCoreApplication.translate
        Wizard.setWindowTitle(_translate("Wizard", "Wizard"))
        self.introWizardPage.setTitle(_translate("Wizard", "Welcome"))
        self.label.setText(_translate("Wizard", "<html><head/><body><p>With this wizard you can construct an MDP file for GROMACS.</p><p>Please note that:</p><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This is not (and is not meant to be) a generally applicable tool, i.e. not all possible MDP options are exposed. If you consider doing anything special (which you might certainly do), you must edit the resulting MDP file to your needs.</li><li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This is only an aid for constructing the files. You should have a deep understanding of MD simulations and GROMACS, in particular. All the responsibility is yours, therefore you must check the resulting MDP file for correctness. The author should not be held liable for incorrect simulation results!</li></ul><p>If you are in doubt of a setting, please check the official GROMACS documentation at <a href=\"https://manual.gromacs.org/documentation/current/user-guide/mdp-options.html\"><span style=\" text-decoration: underline; color:#2980b9;\">https://manual.gromacs.org/documentation/current/user-guide/mdp-options.html</span></a></p></body></html>"))
        self.consentCheckBox.setText(_translate("Wizard", "I\'m aware of my responsibilities"))
        self.simTypeWizardPage.setTitle(_translate("Wizard", "Type of the simulation"))
        self.simTypeWizardPage.setSubTitle(_translate("Wizard", "Select the type of simulation"))
        self.typeEnergyMinimizationRadioButton.setText(_translate("Wizard", "Energ&y minimization"))
        self.typeNVTRadioButton.setText(_translate("Wizard", "NV&T ensemble"))
        self.typeNPTRadioButton.setText(_translate("Wizard", "N&PT ensemble"))
        self.label_8.setText(_translate("Wizard", "Time unit (for display only):"))
        self.timeUnitComboBox.setItemText(0, _translate("Wizard", "fs"))
        self.timeUnitComboBox.setItemText(1, _translate("Wizard", "ps"))
        self.timeUnitComboBox.setItemText(2, _translate("Wizard", "ns"))
        self.timeUnitComboBox.setItemText(3, _translate("Wizard", "ps"))
        self.emWizardPage.setTitle(_translate("Wizard", "Energy minimization parameters"))
        self.emWizardPage.setSubTitle(_translate("Wizard", "Adjust the parameters for energy minimization"))
        self.label_2.setText(_translate("Wizard", "Integrator:"))
        self.label_5.setText(_translate("Wizard", "Frequency of performing 1 steepest descent step [steps]:"))
        self.label_4.setText(_translate("Wizard", "Initial step size [nm]:"))
        self.emIntegratorComboBox.setItemText(0, _translate("Wizard", "steep"))
        self.emIntegratorComboBox.setItemText(1, _translate("Wizard", "cg"))
        self.emIntegratorComboBox.setItemText(2, _translate("Wizard", "l-bfgs"))
        self.label_3.setText(_translate("Wizard", "Tolerance for convergence [kJ/mol/nm]:"))
        self.label_6.setText(_translate("Wizard", "Number of l-BFGS correction steps [steps]:"))
        self.emNstepsSpinBox.setSpecialValueText(_translate("Wizard", "Infinite"))
        self.label_7.setText(_translate("Wizard", "Maximum number of steps [steps]:"))
        self.integratorWizardPage.setTitle(_translate("Wizard", "MD integrator parameters"))
        self.integratorWizardPage.setSubTitle(_translate("Wizard", "Choose the main parameters for the molecular dynamics simulations"))
        self.label_10.setText(_translate("Wizard", "Number of steps:"))
        self.label_9.setText(_translate("Wizard", "Time step:"))
        self.label_12.setText(_translate("Wizard", "Frequency for COMM removal [steps]:"))
        self.label_13.setText(_translate("Wizard", "COMM groups [space separated list]:"))
        self.commTypeComboBox.setItemText(0, _translate("Wizard", "Linear"))
        self.commTypeComboBox.setItemText(1, _translate("Wizard", "Angular"))
        self.commTypeComboBox.setItemText(2, _translate("Wizard", "Linear-acceleration-correction"))
        self.commTypeComboBox.setItemText(3, _translate("Wizard", "None"))
        self.label_11.setText(_translate("Wizard", "Center of mass motion (COMM) removal:"))
        self.nstepsTimeLabel.setText(_translate("Wizard", "TextLabel"))
        self.nstcommTimeLabel.setText(_translate("Wizard", "TextLabel"))
        self.outputWizardPage.setTitle(_translate("Wizard", "Output control"))
        self.outputWizardPage.setSubTitle(_translate("Wizard", "Output / calculation frequencies"))
        self.label_20.setText(_translate("Wizard", "Write energy every n-th step:"))
        self.label_22.setText(_translate("Wizard", "Write XTC file every n-th step:"))
        self.label_21.setText(_translate("Wizard", "Calculate energies every n-th step:"))
        self.label_17.setText(_translate("Wizard", "Write velocities every n-th step:"))
        self.label_19.setText(_translate("Wizard", "Write log file every n-th step:"))
        self.label_18.setText(_translate("Wizard", "Write forces every n-th step:"))
        self.label_23.setText(_translate("Wizard", "Precision of XTC files:"))
        self.label_24.setText(_translate("Wizard", "Groups to write to XTC files (space separated list):"))
        self.label_16.setText(_translate("Wizard", "Write coordinates every n-th step:"))
        self.nstxoutTimeLabel.setText(_translate("Wizard", "TextLabel"))
        self.nstvoutTimeLabel.setText(_translate("Wizard", "TextLabel"))
        self.nstfoutTimeLabel.setText(_translate("Wizard", "TextLabel"))
        self.nstlogTimeLabel.setText(_translate("Wizard", "TextLabel"))
        self.nstenergyTimeLabel.setText(_translate("Wizard", "TextLabel"))
        self.nstcalcenergyTimeLabel.setText(_translate("Wizard", "TextLabel"))
        self.nstxout_compressedTimeLabel.setText(_translate("Wizard", "TextLabel"))
        self.compressed_x_grpsLineEdit.setText(_translate("Wizard", "System"))
        self.neighbourSearchWizardPage.setTitle(_translate("Wizard", "Neighbour searching"))
        self.neighbourSearchWizardPage.setSubTitle(_translate("Wizard", "Neighbour searching options"))
        self.pbcComboBox.setItemText(0, _translate("Wizard", "xyz"))
        self.pbcComboBox.setItemText(1, _translate("Wizard", "xy"))
        self.pbcComboBox.setItemText(2, _translate("Wizard", "no"))
        self.label_15.setText(_translate("Wizard", "Neighbour list update frequency [steps]:"))
        self.label_25.setText(_translate("Wizard", "Neighbour search type:"))
        self.label_14.setText(_translate("Wizard", "Cutoff-scheme:"))
        self.label_26.setText(_translate("Wizard", "Periodic boundary conditions:"))
        self.ns_typeComboBox.setItemText(0, _translate("Wizard", "grid"))
        self.ns_typeComboBox.setItemText(1, _translate("Wizard", "simple"))
        self.label_27.setText(_translate("Wizard", "Verlet buffer tolerance [kJ/mol/ps]:"))
        self.cutoff_schemeComboBox.setItemText(0, _translate("Wizard", "Verlet"))
        self.cutoff_schemeComboBox.setItemText(1, _translate("Wizard", "Group"))
        self.nstListTimeLabel.setText(_translate("Wizard", "TextLabel"))
        self.label_28.setText(_translate("Wizard", "Cut-off distance for the neighbour list [nm]:"))
        self.coulombWizardPage.setTitle(_translate("Wizard", "Electrostatics"))
        self.coulombWizardPage.setSubTitle(_translate("Wizard", "Coulomb interaction"))
        self.label_33.setText(_translate("Wizard", "Relative dielectric constant (0 means infinity):"))
        self.label_30.setText(_translate("Wizard", "Modifier:"))
        self.coulomb_modifierComboBox.setItemText(0, _translate("Wizard", "None"))
        self.coulomb_modifierComboBox.setItemText(1, _translate("Wizard", "Potential-shift-Verlet"))
        self.coulomb_modifierComboBox.setItemText(2, _translate("Wizard", "Potential-shift"))
        self.label_31.setText(_translate("Wizard", "Switching distance [nm]:"))
        self.coulombtypeComboBox.setItemText(0, _translate("Wizard", "PME"))
        self.coulombtypeComboBox.setItemText(1, _translate("Wizard", "PME-Switch"))
        self.coulombtypeComboBox.setItemText(2, _translate("Wizard", "Cut-off"))
        self.coulombtypeComboBox.setItemText(3, _translate("Wizard", "Shift"))
        self.coulombtypeComboBox.setItemText(4, _translate("Wizard", "Reaction-Field-zero"))
        self.coulombtypeComboBox.setItemText(5, _translate("Wizard", "Reaction-Field"))
        self.label_29.setText(_translate("Wizard", "Algorithm:"))
        self.label_32.setText(_translate("Wizard", "Short-range cut-off distance [nm]:"))
        self.label_34.setText(_translate("Wizard", "Relative dielectric constant of the reaction field:"))
        self.vdwWizardPage.setTitle(_translate("Wizard", "Van der Waals"))
        self.vdwWizardPage.setSubTitle(_translate("Wizard", "Van der Waals interactions"))
        self.label_38.setText(_translate("Wizard", "Switching distance [nm]:"))
        self.label_35.setText(_translate("Wizard", "Algorithm:"))
        self.vdwtypeComboBox.setItemText(0, _translate("Wizard", "Cut-off"))
        self.vdwtypeComboBox.setItemText(1, _translate("Wizard", "PME"))
        self.vdwtypeComboBox.setItemText(2, _translate("Wizard", "Shift"))
        self.vdwtypeComboBox.setItemText(3, _translate("Wizard", "Switch"))
        self.label_36.setText(_translate("Wizard", "Modifier:"))
        self.vdw_modifierComboBox.setItemText(0, _translate("Wizard", "Potential-shift-Verlet"))
        self.vdw_modifierComboBox.setItemText(1, _translate("Wizard", "Potential-shift"))
        self.vdw_modifierComboBox.setItemText(2, _translate("Wizard", "None"))
        self.vdw_modifierComboBox.setItemText(3, _translate("Wizard", "Force-switch"))
        self.vdw_modifierComboBox.setItemText(4, _translate("Wizard", "Potential-switch"))
        self.label_37.setText(_translate("Wizard", "Cut-off distance for the short range VdW [nm]:"))
        self.label_39.setText(_translate("Wizard", "Dispersion correction:"))
        self.dispcorrComboBox.setItemText(0, _translate("Wizard", "no"))
        self.dispcorrComboBox.setItemText(1, _translate("Wizard", "EnerPres"))
        self.dispcorrComboBox.setItemText(2, _translate("Wizard", "Ener"))
        self.ewaldWizardPage.setTitle(_translate("Wizard", "Ewald & Constraints"))
        self.ewaldWizardPage.setSubTitle(_translate("Wizard", "Settings for Ewald summation and bond constraint algorithms"))
        self.label_57.setText(_translate("Wizard", "Constraint algorithm:"))
        self.label_59.setText(_translate("Wizard", "LINCS order:"))
        self.constraintsComboBox.setItemText(0, _translate("Wizard", "none"))
        self.constraintsComboBox.setItemText(1, _translate("Wizard", "h-bonds"))
        self.constraintsComboBox.setItemText(2, _translate("Wizard", "all-bonds"))
        self.constraintsComboBox.setItemText(3, _translate("Wizard", "h-angles"))
        self.constraintsComboBox.setItemText(4, _translate("Wizard", "all-angles"))
        self.label_58.setText(_translate("Wizard", "LINCS"))
        self.label_40.setText(_translate("Wizard", "Fourier spacing [nm]:"))
        self.label_60.setText(_translate("Wizard", "Numbr of LINCS iterations:"))
        self.label_56.setText(_translate("Wizard", "Apply constraints to:"))
        self.label_41.setText(_translate("Wizard", "PME interpolation order:"))
        self.label_61.setText(_translate("Wizard", "LINCS warning angle threshold [deg]:"))
        self.tcouplWizardPage.setTitle(_translate("Wizard", "Temperature coupling"))
        self.tcouplWizardPage.setSubTitle(_translate("Wizard", "Thermostat parameters"))
        self.nsttcoupleTimeLabel.setText(_translate("Wizard", "TextLabel"))
        self.nsttcoupleSpinBox.setSpecialValueText(_translate("Wizard", "=nstlist"))
        self.label_42.setText(_translate("Wizard", "Algorithm:"))
        self.label_46.setText(_translate("Wizard", "Reference temperature [K, common for all groups]:"))
        self.label_47.setText(_translate("Wizard", "Time constant for coupling [ps, common for all groups]:"))
        self.label_43.setText(_translate("Wizard", "Temperature coupling frequency [steps]:"))
        self.label_45.setText(_translate("Wizard", "Temperature coupling groups [space separated list]:"))
        self.tcouplComboBox.setItemText(0, _translate("Wizard", "berendsen"))
        self.tcouplComboBox.setItemText(1, _translate("Wizard", "nose-hoover"))
        self.tcouplComboBox.setItemText(2, _translate("Wizard", "v-rescale"))
        self.groupBox.setTitle(_translate("Wizard", "Veloci&ty generation"))
        self.label_44.setText(_translate("Wizard", "Temperature [K]:"))
        self.label_48.setText(_translate("Wizard", "Random seed:"))
        self.gen_seedSpinBox.setSpecialValueText(_translate("Wizard", "Pseudo-random"))
        self.pcouplWizardPage.setTitle(_translate("Wizard", "Pressure coupling"))
        self.pcouplWizardPage.setSubTitle(_translate("Wizard", "Tune the barostat"))
        self.label_49.setText(_translate("Wizard", "Algorithm:"))
        self.label_50.setText(_translate("Wizard", "Coupling type:"))
        self.nstpcoupleSpinBox.setSpecialValueText(_translate("Wizard", "=nstlist"))
        self.nstpcoupleTimeLabel.setText(_translate("Wizard", "TextLabel"))
        self.pcopultypeComboBox.setItemText(0, _translate("Wizard", "isotropic"))
        self.pcopultypeComboBox.setItemText(1, _translate("Wizard", "semiisotropic"))
        self.pcopultypeComboBox.setItemText(2, _translate("Wizard", "surface-tension"))
        self.label_54.setText(_translate("Wizard", "Reference pressure [bar]:"))
        self.label_52.setText(_translate("Wizard", "Time constant for pressure coupling [ps]:"))
        self.label_51.setText(_translate("Wizard", "Pressure coupling frequency [steps]:"))
        self.pcouplComboBox.setItemText(0, _translate("Wizard", "Berendsen"))
        self.pcouplComboBox.setItemText(1, _translate("Wizard", "Parrinello-Rahman"))
        self.label_53.setText(_translate("Wizard", "Compressibility [1/bar]:"))
        self.label_55.setText(_translate("Wizard", "Reference coordinate scaling:"))
        self.refcoord_scalingComboBox.setItemText(0, _translate("Wizard", "no"))
        self.refcoord_scalingComboBox.setItemText(1, _translate("Wizard", "all"))
        self.refcoord_scalingComboBox.setItemText(2, _translate("Wizard", "com"))
        self.endWizardPage.setTitle(_translate("Wizard", "Finished"))
        self.endWizardPage.setSubTitle(_translate("Wizard", "Please select a file to save your MDP file to..."))

from wpintro import WPIntro
